### ISSUE TITLE
Add an example with changing order of intersections and sets

### ISSUE THREAD

**Issue by krassowski** [krassowski/complex-upset#10]
- [x] allow using the order of sets from the groups argument (`sort_sets=FALSE`) - see https://github.com/krassowski/complex-upset/issues/13#issuecomment-603337457
- [x] allow disabling intersection sorting by size (`sort_intersections=FALSE`)
- [x] allow changing descending/ascending sorting
- [x] add examples

**Comment by krassowski** [comment]
Fixed at ed6dd96d59a93d81a2888a91e8cd17efa5040f4a

**Comment by Bingqing-Yang** [comment]
Hi. Thank you for your sharing. I have a question about ComplexUpset. There are a lot of blanks in the intersection size panel, so I want to add a title in it not above it. When I use 'ggtitle('All patients') +
  theme(plot.title = element_text(hjust = 0.5, vjust = -3))' the drawing area cover a half title. So my question is how to add a title among the intersection size panel but not cover it. Thank you for your support!
