### ISSUE TITLE
How to extract subsets of elements presented in intersection bar

### ISSUE THREAD

**Issue by cejote** [krassowski/complex-upset#125]
How can I get a list (data.frame) of all elements which are shown in the bars? In section _0. Basic usage_ we find 154 elements in the group of Drama+Comedy but I failed obtain such a subset from the object returned by _upset_data()_. Do you have any advice how I could obtain such filtered lists? Many thanks!

**Comment by krassowski** [comment]
It is present for example in `upset_data(movies, genres)$sizes`:

![Screenshot from 2021-07-21 10-12-56](https://user-images.githubusercontent.com/5832902/126463708-dd0e1bf5-f9ff-4ada-afd4-dc262a45c787.png)

**Comment by cejote** [comment]
Thanks for the quick response. I confirm that number but but cannot see how to extract the 154 elements that establish the group. When using `intersections_data$with_sizes %>% filter(exclusive_intersection=="Comedy-Drama")` I get 3234 elements while `intersections_data$with_sizes %>% filter(exclusive_intersection_size==154)` still gives 1393 elements. Next, I tried to make the list distinct based on the `(title, year)` but this does not reduce the set size to the expected 154 elements.

**Comment by krassowski** [comment]
Thanks for clarifying, sorry I misread your question! That would be:

```R
upset_data(movies, genres)$with_sizes %>%
    filter(intersection=="Comedy-Drama" & in_exclusive_intersection == TRUE)
```

Or for inclusive intersection:

```R
upset_data(movies, genres)$with_sizes %>%
    filter(intersection=="Comedy-Drama" & in_inclusive_intersection == TRUE)
```

and so on.

**Comment by krassowski** [comment]
> Next, I tried to make the list distinct based on the (title, year) but this does not reduce the set size to the expected 154 elements.

I do not know why filtering did not work for you, it seems to work fine for me:

```R
df = upset_data(movies, genres)$with_sizes %>%
    filter(exclusive_intersection=="Comedy-Drama") %>%
    distinct(title, year)
nrow(df)
```

> 154

**Comment by cejote** [comment]
Thanks so much, this is exactly what I was looking for! Now I can even shape the output into a grouped tibble for post analyses of any group combinations. Awesome! :-))
