### ISSUE TITLE
Simple case use, does it work properly? 

### ISSUE THREAD

**Issue by Axze-rgb** [krassowski/complex-upset#126]
Hello, 

Just checking this is the way to go, I have a data.table that looks like 

```
    callvariants deepvariant  GATK strelka                ID
      1:         TRUE       FALSE  TRUE    TRUE      Chrom_3_793T
      2:         TRUE       FALSE  TRUE    TRUE     Chrom_3_4024G
      3:         TRUE       FALSE FALSE    TRUE     Chrom_3_4034G
      4:         TRUE       FALSE FALSE    TRUE     Chrom_3_4035A
      5:         TRUE       FALSE  TRUE    TRUE     Chrom_3_4061T
     ---                                                         
```

I want to check if each ID is present in any combination of callers (the first 4 columns)

```
caller = colnames(df3)[1:4]
upset(df3, caller, name = 'caller')
```
The result seems to be what I need. Sorry it's a basic question but I want to make sure. 

Thanks a lot

**Comment by krassowski** [comment]
Yes, this looks like a proper use of this package. I would recommend following the example [basic usage](https://krassowski.github.io/complex-upset/articles/Examples_R.html#0-basic-usage) guide in the documentation as it describes important differences between modes. Also, checking the results "manually" by using only the a first few rows of the data frame can be useful to ensure you follow what is going on.

**Comment by Axze-rgb** [comment]
Thanks!
