### ISSUE TITLE
Ordering intersection matrix and font size

### ISSUE THREAD

**Issue by aderzelle** [krassowski/complex-upset#13]
Hello,

is this possible? 
Also, how does one change the font size?

**Comment by krassowski** [comment]
For a global font size change, just update the themes:

```R
upset(
    movies, genres,
    base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),
    min_size=100,
    width_ratio=0.1,
    themes=upset_default_themes(text=element_text(size=30))
)
```

![sizeupset](https://user-images.githubusercontent.com/5832902/77442322-3fe17c80-6de2-11ea-8f2d-d9b46c0e5def.png)

**Comment by aderzelle** [comment]
And for ordering? 

Btw, setting width_ratio to 1 results in the intersection size not being displayed

![example](https://user-images.githubusercontent.com/23341393/77444479-2cd3aa00-6dec-11ea-81bd-33ba844dc102.png)

**Comment by krassowski** [comment]
To modify only certain elements:

```R
upset_modify_themes = function(to_update)  {
    c(
        sapply(
            names(to_update),
            function(name) {
                c(upset_themes[[name]], to_update[name])
            }
        ),
        upset_themes[setdiff(names(upset_themes), names(to_update))]
    )
}

upset(
    movies, genres,
    base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),
    min_size=100,
    width_ratio=0.1,
    themes=upset_modify_themes(
        list(
            'intersections_matrix'=theme(text=element_text(size=30)),
            'overall_sizes'=theme(axis.text.x=element_text(angle=90))
        )
    )
)
```

![theme specific updates](https://user-images.githubusercontent.com/5832902/77445939-9dc39380-6de5-11ea-880d-c7f767be59d7.png)

I will add `upset_modify_themes` in the next release.

**Comment by krassowski** [comment]
Wha exactly do you mean by "Ordering intersection matrix"? Changing the order of rows, or columns?

**Comment by aderzelle** [comment]
Euh yes sorry, order of rows, in the example you posted for example, let's say I want Romance to be at the top, then Animation, Documentary, etc ...

**Comment by krassowski** [comment]
1. update the package with:
```R
devtools::install_github("krassowski/complex-upset")
```
2. restart R if needed
3. add `sort_sets=FALSE`

```R
upset(
    movies, genres,
    base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),
    min_size=100,
    width_ratio=0.1,
    sort_sets=FALSE
)
```

![not_sorted_sets](https://user-images.githubusercontent.com/5832902/77449677-293f2380-6dea-11ea-9ebb-8c5704a968b0.png)

the order is taken from the second argument, here `genres`:

![Screenshot from 2020-03-24 16-11-16](https://user-images.githubusercontent.com/5832902/77449667-23494280-6dea-11ea-9232-851ebf4e92d9.png)
