### ISSUE TITLE
error: could not find function "upset_set_size"

### ISSUE THREAD

**Issue by MilouArts** [krassowski/complex-upset#131]
I was already running into this error before and fixing the other error made me check with the standard dataset and also there I'm running into the same error:

Error in upset_set_size(geom = geom_bar(aes(fill = mpaa, x = group), width = 0.8),  : 
  could not find function "upset_set_size"

from the manual:
```{r}  
ComplexUpset::upset(
  movies, genres,
  min_size=10,
  width_ratio=0.3,
  set_sizes=(
    upset_set_size(
      geom=geom_bar(
        aes(fill=mpaa, x=group),
        width=0.8
      ),
      position='right'
    )
  ),
  # moves legends over the set sizes
  guides='over')
```

**Comment by krassowski** [comment]
I think you may be missing a `library(ComplexUpset)` call. Or you could use `ComplexUpset::upset_set_size`.

**Comment by MilouArts** [comment]
Ah I see.. thanks!
