### ISSUE TITLE
Is it possible to plot the percentage of sets?

### ISSUE THREAD

**Issue by tomleung1996** [krassowski/complex-upset#133]
Hi, thanks for your wonderful software!

I was trying to generate a figure like Fig.2 in [this paper](https://arxiv.org/ftp/arxiv/papers/2004/2004.14329.pdf), which was also generated by `complex-upset`.

However, I am not familiar with R and found it really hard to modify the default behavior of `complex-upset`, especially showing the percentage of each set. I have read `3.7 Showing percentages` in the document but it was not the desired behavior. What I want is to show the actual percentage that a set accounts for in all the samples (percentages should sum up to 1).

Also, changing the behavior of the legend in the lower-left corner is even harder for me. Can you help me with this problem? 

Thanks a lot!

**Comment by tomleung1996** [comment]
In addition, there are some behaviors that I don't understand. For example, there are 913 Drama movies in the dataset (1813 samples), why the upset plot said there were 429?

**Comment by tomleung1996** [comment]
I have tried this 

```
upset(
    movies, genres,
    min_size=10,
    base_annotations=list(
        'Intersection size'=(
            intersection_size(
                text_aes=aes(
                    y=ifelse(
                        ..count.. <= 0.85 * max(..count..),
                        ..count../sum(..count..),
                        (..count.. * 0.85) / sum(..count..)
                    )
                )
            )
            + aes(y=..count../sum(..count..))
            + ylab('Intersection size percentage')
            + scale_y_continuous(labels=scales::label_percent(accuracy=1))
        )
    )
)
```

but it resulted in an error: 

```
Error: stat_summary requires the following missing aesthetics: y
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Ignoring unknown parameters: text_aes 
```

**Comment by tomleung1996** [comment]
The best I could do is shown below, but the y axis was still wrong.

![plot_zoom_png](https://user-images.githubusercontent.com/11535152/128692635-a6e550d4-255a-4c1b-9a7b-e9fd898286f3.png)

The code is:

```
upset(
  movies, genres,
  min_size=10,
  base_annotations = list(
    'Intersection size'=intersection_size(text_mapping=aes(label=paste0(round(
      !!get_size_mode('exclusive_intersection')/nrow(movies) * 100, 1), ''))) 
    + ylab('Intersection %')
  ),
  set_sizes=(FALSE)
)
```

**Comment by krassowski** [comment]
Hi, just as a quick check, did you also see section [`10. Display percentages`](https://krassowski.github.io/complex-upset/articles/Examples_R.html#10-display-percentages)? Does any of these examples answer your question?

**Comment by krassowski** [comment]
> Also, changing the behavior of the legend in the lower-left corner is even harder for me. Can you help me with this problem?

Sure! If you can make a sketch of what you are trying to accomplish I should be able to help with this and if there is any odd behaviour, unhelpful error messages or the intuitive way of doing things does not work that needs fixing.

**Comment by tomleung1996** [comment]
> Hi, just as a quick check, did you also see section [`10. Display percentages`](https://krassowski.github.io/complex-upset/articles/Examples_R.html#10-display-percentages)? Does any of these examples answer your question?

Yes, I checked that section and found it wasn't helpful. My desired behavior is similar to `intersection_ratio` but not the same. I want the ratio  = set_size / nrow(movies). 

I thought the upset plot I generated above was just replacing the text label with the underlying calculation untouched. My desired outcome is:
![微信截图_20210809190324](https://user-images.githubusercontent.com/11535152/128696924-02cc0f19-e751-45a7-a68d-421b7853f24f.png)

and the best I can do is:
![微信截图_20210809190425](https://user-images.githubusercontent.com/11535152/128697022-3a27471b-cf12-4ff7-a4eb-dec10d41407b.png)

and my code is:

```
upset(
  movies, genres,
  min_size=10,
  base_annotations = list(
    'Intersection size'=intersection_size(text_mapping=aes(label=paste0(round(
      !!get_size_mode('exclusive_intersection')/nrow(movies) * 100, 1), ''))) 
    + ylab('Intersection %')
  ),
  set_sizes=(FALSE)
)
```

I hope that my description is clear enough XD

**Comment by tomleung1996** [comment]
Maybe more precisely, can I replace the `denominator ` in `intersection_ratio` with the number of all samples?

**Comment by krassowski** [comment]
Yes that helps! In ggplot2 which is what this package is built on top of to adjust the labels of axis we can use `scale_(x/y)_*()` functions, and [`scale_y_continuous`](https://ggplot2.tidyverse.org/reference/scale_continuous.html) is a good candidate here. You can achieve what you want with:

```R
upset(
    movies, genres,
    min_size=10,
    base_annotations = list(
        'Intersection size'=(
            intersection_size(
                text_mapping=aes(
                    label=paste0(round(!!get_size_mode('exclusive_intersection')/nrow(movies) * 100, 1), '')
            ))
            + ylab('Intersection %')
            + scale_y_continuous(labels=scales::percent_format(scale=100 / nrow(movies)))
        )
    ),
    set_sizes=(FALSE)
)
```

which gives:

![image](https://user-images.githubusercontent.com/5832902/128698612-582eb22e-1f89-4dde-ba16-5471ec9a5428.png)

It actually makes sense to make it easier to specify `nrow(movies)` using the `upset_text_percentage()` helper. I will look into this and add this as an example. Thank you for bringing this up.

**Comment by krassowski** [comment]
Also if you want the breaks at specific round values:

```R
upset(
    movies, genres,
    min_size=10,
    base_annotations = list(
        'Intersection size'=(
            intersection_size(
                text_mapping=aes(
                    label=paste0(round(!!get_size_mode('exclusive_intersection')/nrow(movies) * 100, 1), '')
                )
            )
            + ylab('Intersection %')
            + scale_y_continuous(
                labels=scales::percent_format(scale=100 / nrow(movies)),
                breaks=c(0, 5, 10, 15, 20) / 100 * nrow(movies)
            )
        )
    ),
    set_sizes=(FALSE)
)
```

![image](https://user-images.githubusercontent.com/5832902/128699062-ca4cac48-f7b1-4053-9e3f-8b33ed2c416c.png)

**Comment by tomleung1996** [comment]
Thank you very much! Your last reply just solved what I was going to say!

I still have a stupid question: Can this package handle hundreds of millions of rows of data? I am running this on a server with 128GB RAM.

**Comment by krassowski** [comment]
If you mean 10^9 this can be difficult; we had reports that 10^9 does not fit on 64GB machines: https://github.com/krassowski/complex-upset/issues/28, but I never tried it with a 128GB machine and don't have the curves to demonstrate how it scales - well that would be good to have in the docs...

Aspirationally 10^6 should not be a problem with 128GB, but this is not only a function of the number of rows but also on the number of intersections. There are some old benchmarks in https://github.com/krassowski/complex-upset/issues/12#issuecomment-739437863 but I think those are outdated (the package is slower by default now to offer more flexibility with multiple modes, but we can improve here if needed).

This package was meant to allow plotting individual data points and the bar plots are just the simplest thing that it can do. We could have a special routine for dealing with large data when only summary statistics are required, but this was not the original goal.

**Comment by tomleung1996** [comment]
I see. I would let you know if I succeed! Thank you for your help!

**Comment by tomleung1996** [comment]
I did it! It took about 30 minutes to generate the upset plot for a dataset consists of 20,000,000 rows and 6 categories. It used up to 100GB RAM (min_size=200000).
