### ISSUE TITLE
How to change the bar width?

### ISSUE THREAD

**Issue by tomleung1996** [krassowski/complex-upset#138]
I know this must be a stupid question...

I have searched that I may use `geom_bar(width = XXX)` to change the bar width but I don't know where to put this code in `upset`.

**Comment by tomleung1996** [comment]
Also, the font size?

**Comment by krassowski** [comment]
All remaining arguments passed to `intersection_size` will be passed to `geom_bar`, [as explained in the documentation](https://krassowski.github.io/complex-upset/reference/intersection_size.html) so you can pass `width=0.3` like that:

```R
upset(
    movies,
    genres,
    base_annotations=list(
        'Intersection size'=intersection_size(
            text=list(size=7),
            width=0.3,
            text_colors=c(on_background='black', on_bar='orange')
        )
    ),
    min_size=10,
    width_ratio=0.1
)
```

![image](https://user-images.githubusercontent.com/5832902/129357761-8bb8e0fb-e7ef-45c9-9307-2b791e7304b4.png)

**Comment by tomleung1996** [comment]
Thank you! You're always so helpful!

I am still struggling with my big dataset. I can calculate all the sizes of possible combinations by myself, but I have to prepare the input file for `ComplexUpset` and let it does the job, which consumes too much memory.

Is it possible that I could just pass some calculated values (the height of each bar, ignoring small groups) and the corresponding ways of set combinations and get the plot? All I need is the bar chart and the combinations (ignoring small groups).

**Comment by krassowski** [comment]
I responded in: https://github.com/krassowski/complex-upset/issues/137#issuecomment-898429483 - I will look into this after my day job, this weekend.
