### ISSUE TITLE
How to keep sets with set size equals to zero in the plot?

### ISSUE THREAD

**Issue by VirtualSpaceman** [krassowski/complex-upset#139]
Hi! Thanks for the great package!

**Objective**
Show the set sizes in bar plot when intersection size is zero. The current behavior just hide intersections which set sizes are zero. I also tested the parameter ``keep_empty_groups=TRUE``, but did not get the expected result.   

**Code**

```R
upset(data,
      model_names,
      keep_empty_groups=TRUE,
      set_sizes=FALSE,
      sort_sets=FALSE,
      sort_intersections='ascending',
      sort_intersections_by='degree',
      name=paste(ds,"_",percent, sep=''),
      matrix=intersection_matrix(
        geom=geom_point(shape='circle filled', size=3)
        ),
      base_annotations = list(
        'Intersection size'=(
            intersection_size(text=list(size=5),
            width=0.4,
            text_colors=c(on_background='black', on_bar='black'),
            bar_number_threshold=1.0)
            + theme(
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank())
        )
    ),
    queries=query_by_degree(
        data,
        model_names,
        params_by_degree=list(
        '0'=list(fill='green'),
        '1'=list(fill='red'),
        '2'=list(fill='purple'),
        '3'=list(fill='blue'),
        '4'=list(fill='orange')
        ),
            ,
        shared=list(
            only_components=c("intersections_matrix", "Intersection size"),
            color='black'
        )

      ),
      themes=upset_default_themes(text=element_text(size=14)),
    
    ) 
```

**Screenshot or illustration**
Below I generated two plots showing the problem. The first one shows all the sets correctly. Note that one of the intersections is circled. This circled intersection is not present in the second plot. I suppose that since the size of the set in the second case is zero, this amount did not appear in the second plot. The expected behavior in my case is that all intersections are shown, but with the correct quantities (even equal to zero) to maintain consistency.  

![upset_10_percent_atlas-clinical](https://user-images.githubusercontent.com/25913656/131385718-930667b9-f5ec-4133-a671-3cedf587404c.png)
![upset_100_percent_atlas-clinical](https://user-images.githubusercontent.com/25913656/131385723-8a8ff2c7-ee36-4dac-bed9-82a82a054502.png)

**Context (required)**

ComplexUpset version: 1.3.0

<details>
<summary>R version details</summary>

```R
$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "6.3"

$year
[1] "2020"

$month
[1] "02"

$day
[1] "29"

$`svn rev`
[1] "77875"

$language
[1] "R"

$version.string
[1] "R version 3.6.3 (2020-02-29)"

$nickname
[1] "Holding the Windsock"
```

</details>

<details>
<summary>R session information</summary>

```R
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.3
```

</details>

**Comment by krassowski** [comment]
Hi! Could please try passing `intersections='all'` and let me know if this does what you would like to achieve?

**Comment by VirtualSpaceman** [comment]
It worked, but still have a few issues. First, the text showing the intersection size for the empty set has gone to zero. I don't know why that happened, but the bar height seen correct to me.

![100_percent_chart-copy](https://user-images.githubusercontent.com/25913656/131401407-efd4e473-e509-4af1-a2fc-6c9e982e9845.png)

Setting ``intersections='all'``is totally fine, but the intersection color provided by query doesn't. I suppose it is easy to fix, since I just need to change the ``query_by_degree``function. But, above the zero-size intersections seems to be just white, without  any bar plot plus set size annotation.  Is there any way to add just a tiny bar with the correct (zero) annotation as depicted in the following image?   

![100_percent_chart](https://user-images.githubusercontent.com/25913656/131396003-f9c4a47c-a33a-4e08-8905-83ec61631f07.png)

**Comment by krassowski** [comment]
Ouch, that's not good. I will work to fix this. It would help if you could create a simple reproducible example (either by sharing the data used for the plots above, or by sub-setting the `movies` example from [the README](https://github.com/krassowski/complex-upset#showcase)).

**Comment by VirtualSpaceman** [comment]
Sure! 

Minor example by sub-setting the ``movies`` dataset: 

```R

%%capture
%load_ext rpy2.ipython 

%%R
library(ggplot2)
library(ComplexUpset)

from pydataset import data as load_data
movies = load_data('movies').dropna()
genres = list(movies.columns[-3:])

%%R -w 800 -h 300 -i movies -i genres
upset(movies, genres, 
      name='genre',
      sort_intersections='ascending',
      sort_intersections_by='degree',
      width_ratio=0.1, 
      intersections='all')

```

![teste](https://user-images.githubusercontent.com/25913656/131407599-61a99a12-47da-4596-9c80-d0f0999bf078.png)
