### ISSUE TITLE
group by "sets" removes bar with 0 sets

### ISSUE THREAD

**Issue by sannagudmundsson** [krassowski/complex-upset#141]
**Objective**
I want to sort my upset plot (ComplexUpset) by grouping the sets as in the first screenshot. However, when I do so by using group_by='sets', the bar that indicates the number of occurrences that has no sets (n=13 seen in second screenshot) is removed, and I want to keep that bar. How do I group by set but keep the bar indicating no sets (n=13)? I tried playing around with sort_intersections and sort_intersections_by but no luck. Is there an easy fix for this? Thank you!

**Code**

```R
upset(df, 
      flags, 
      keep_empty_groups=TRUE,
      group_by="sets",
      width_ratio=0.2,
      min_size = 1,
       matrix=(
        intersection_matrix(geom=geom_point(shape='circle', size=2)))
      )
```

**Screenshot or illustration**
![image](https://user-images.githubusercontent.com/44973249/144129928-bd01ff93-a14a-4547-981e-6070c54006f0.png)
![image](https://user-images.githubusercontent.com/44973249/144130004-ec0afa0d-3a5b-41aa-b672-cb2d6bd50e3d.png)

**Context (required)**
ComplexUpset version: 1.3.1

<details>
<summary>R version details</summary>

```R
> R.version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.4                         
year           2021                        
month          02                          
day            15                          
svn rev        80002                       
language       R                           
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book

**Comment by krassowski** [comment]
Thank you for highlighting this. I am working on a fix and hope to get it out soon.

**Comment by krassowski** [comment]
Hi @sannagudmundsson thanks again for reporting it. The degree zero intersection will be shown (no changes to your code are required) in the latest 1.3.2 version (not yet available on CRAN). To install it, use:

```R
if(!require(devtools)) install.packages("devtools")
devtools::install_github("krassowski/complex-upset")
```

I will just note that `keep_empty_groups` is unrelated. In future if you decide that you no longer want include the zero degree intersection, you can hide it with `min_degree=1`.
