### ISSUE TITLE
Alternative Barplot

### ISSUE THREAD

**Issue by MichWeb75** [krassowski/complex-upset#146]
Hi,
I often get asked the question what is the most frequent combination of items in a upset plot or venn diagram.
For example if 
```
resList <- list()
resList[["A"]] <- c(1:5,6:15)
resList[["B"]] <- c(1:5)
resList[["C"]] <- c(1:5,6:15)
resList[["D"]] <- c(1:5,6:15)
```
A,C,D is the largest with 15 occurences. However in a upset plot it would be separated into two bars, one with 4 sets (A,B,C,D) size 5 and 3 sets (A,C,D) with size 10.
In summary, my question refers to the way how the upset function calculates the set sizes And if it is possible to integrate larger sets in the counts of smaller overlapping sets.

Best, Michael

**Comment by krassowski** [comment]
I think that you may wish to change the `mode`; from your very brief plain-English description it is not clear to me what exactly you try to achieve. The available modes are explained in depth in [the documentation, in `0.2 Region selection modes` chapter](https://krassowski.github.io/complex-upset/articles/Examples_R.html#0-2-region-selection-modes). Does it help, or are you after something else?

**Comment by MichWeb75** [comment]
Perfect, I was not aware that such modes exist! Thank you for this advice!
