### ISSUE TITLE
Set names on both sides of the intersection matrix

### ISSUE THREAD

**Issue by Julkut** [krassowski/complex-upset#158]
Hi.
Is there a way to duplicate the set names on both sides of the intersection matrix? I have quite a few intersections and would like to have set names both on the left and on the right hand side of the intersection matrix.
I would appreciate any advice.
Thanks beforehand!
Best,
Julia

**Comment by krassowski** [comment]
A clean solution requires `scale_discrete` to accept `sec.axis` which is a change needed in `ggplot2` itself. There is an issue open for this:  https://github.com/tidyverse/ggplot2/issues/3171 and in fact, as of today, it is the most requested issue in `ggplot2` repository (you can go to the issue and upvote it too).

For now we can use a workaround from https://github.com/tidyverse/ggplot2/issues/3171#issuecomment-614084750 works (but it may stop working in future), and requires copy-pasting:

```R
library(ggplot2)

guide_axis_label_trans <- function(label_trans = identity, ...) {
  axis_guide <- guide_axis(...)
  axis_guide$label_trans <- rlang::as_function(label_trans)
  class(axis_guide) <- c("guide_axis_trans", class(axis_guide))
  axis_guide
}

guide_train.guide_axis_trans <- function(x, ...) {
  trained <- NextMethod()
  trained$key$.label <- x$label_trans(trained$key$.label)
  trained
}
```

and then using it with `ComplexUpset` like this:

```R
upset(
    movies, genres, name='genre', min_size=10,
    matrix=(
        intersection_matrix()
        + guides(y.sec=guide_axis_label_trans(identity))
    )
)
```

![image](https://user-images.githubusercontent.com/5832902/187536100-d2bf6bc5-cf2f-4eca-998c-f61ff419d2b5.png)

**Comment by Julkut** [comment]
Thank you very much! This helped!
