### ISSUE TITLE
element `strip.clip` is not defined when using upset function with documentation's dataset

### ISSUE THREAD

**Issue by Benjamin-Valderrama** [krassowski/complex-upset#165]
I'm following the tutorial in the package's documentation. Everything works fine while I'm working with the movie dataset. However, when I use the upset function as follows:

```
library(ggplot2)
library(ComplexUpset)

movies = as.data.frame(ggplot2movies::movies)
genres = colnames(movies)[18:24]
movies[genres] = movies[genres] == 1
movies[movies$mpaa == '', 'mpaa'] = NA
movies = na.omit(movies)
movies
```

I have the next error:

```
Error:
! Theme element `strip.clip` is not defined in the element hierarchy.
```

**Objective**
What am I doing wrong? Of course I'm trying to do the same with my own dataset and, despite of formatting my dataset in the same format as the one depicted in the documentation, the upset function gives me the same error.

ComplexUpset version: ‘1.3.3’

```R
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.0                              
year           2022                             
month          04                               
day            22                               
svn rev        82229                            
language       R                                
version.string R version 4.2.0 (2022-04-22 ucrt)
nickname       Vigorous Calisthenics 
```

**Comment by krassowski** [comment]
What version of ggplot do you have installed? Can you add the code of the plot itself too?

**Comment by Benjamin-Valderrama** [comment]
I'm using ggplot2 3.3.6. Sorry,I forgot to copy that part.

I'm running this:

`upset(movies, genres, name='genre', width_ratio=0.1)`

Which is exactly what I is writen in the section "R examples" from the documentation of the package.

Thank you in advance.

**Comment by Benjamin-Valderrama** [comment]
I forgot to mention that after updating ggplot2 to version 3.4.0 and the problem persist.

**Comment by Benjamin-Valderrama** [comment]
It is solved. I updated `vctrs` package from `4.0.1` to `5.0.1` and now the `upset` function works. Thank you! It is a great package with a lot of functionalities. Looking forward to use it in my next work. 

Cheers!

**Comment by krassowski** [comment]
Thanks for getting back with the solution! Good luck and if you have any other questions please let me know.
