### ISSUE TITLE
Reduce the size of circles when the size of the global figure is diminished.

### ISSUE THREAD

**Issue by ZheFrench** [krassowski/complex-upset#174]
I'm trying to reduce the diameters of the circles.  
When I reduce the size of my figure , at some point circles overlaps and it's not clean.  
I would like to remove the overlap between black/grey circles.  
This what I produced for now [here](https://raw.githubusercontent.com/ZheFrench/pics/master/Upset_Cancer_cell.svg).

**Comment by krassowski** [comment]
Did you try changing `size` for `geom_point` as in this example: https://krassowski.github.io/complex-upset/articles/Examples_R.html#adjusting-the-intersection-matrix ?

**Comment by ZheFrench** [comment]
Nope, but this is a good advice ! I'll give a try.
I end up with  ` height_ratio=1,` who did the job. 
Tks.
