### ISSUE TITLE
Incorrect intersection size

### ISSUE THREAD

**Issue by bagcik1lumc** [krassowski/complex-upset#179]
**Objective**
Display intersection size as percentage of total observations. Input is a binary matrix of "1" and "0". 

**Code**

```R
upset(
  M1_BinaryMatrix,
  colnames(M1_BinaryMatrix),
  n_intersections=5,
  sort_intersections_by='ratio',
  #
  set_sizes=(
    upset_set_size(position='right', geom = geom_bar(width = .9))
    + geom_text(aes(label=paste0(round((..count../nrow(M1_BinaryMatrix))*100), '%')), hjust=1.1, stat='count', color='white')
    + expand_limits(y=1000)
    + ylab("")
    + theme(axis.text.x = element_blank(), 
            panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(),
            panel.background = element_blank()
    )
  ),
  #
  base_annotations=list(
    'Intersection size'=intersection_size(text_mapping=aes(label=paste0(round(
      !!get_size_mode('inclusive_intersection')/nrow(M1_BinaryMatrix) * 100
    ), '%')))
    + ylab("")
    + theme(axis.text.y = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank()
    )
  ),
  #
  height_ratio=0.7,
  width_ratio=0.3,
  name="",
  wrap=TRUE,
  stripes='white', # c(alpha('grey90', 0.45), alpha('white', 0.3)),
  matrix = intersection_matrix(    
    geom=geom_point(
      shape='square',
      size=4
    ),
    segment=geom_segment(
      linetype='solid'
    ), 
    outline_color=list(
      active='darkorange3',
      inactive='grey70'
    )
  )
  #
) + labs(title = "", caption = "")
```

**Screenshot or illustration**
Currently, intersection size is based on only the "1" and not on the "0". However, "0"s should also be part of the intersection. The output of the UpSet plot is now equal to **Russel-Rao similarity**, but it should be equal to **Rand's similarity**.

**Comment by krassowski** [comment]
1) This issue is not reproducible without specifying what `M1_BinaryMatrix` is.
2) Please remove all unrelated code.
3) Please clarify why a certain way of visualising data is _correct_ and the other in is not.

**Comment by bagcik1lumc** [comment]
The UpSet plot only considers the observations containing a "1", while a "0" is also an observation and should be part of the inclusive intersection (alias: intersect).

**Comment by krassowski** [comment]
This does not answer my questions. I do not know what "1" is or "0". You need to provide a reproducible example.

**Comment by bagcik1lumc** [comment]
How can I provide that matrix? It's almost 1 gb

**Comment by krassowski** [comment]
You don't. Instead provide a [minimal reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).

**Comment by bagcik1lumc** [comment]
`structure(list(`KM-G4` = c(0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L
), `KM-E4` = c(0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L), `KM-G15` = c(0L, 
1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L), `KM-E15` = c(0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
1L, 0L, 0L, 0L, 0L), `AC-G4` = c(0L, 1L, 1L, 1L, 1L, 1L, 1L, 
0L, 1L, 1L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 1L, 0L, 1L, 1L, 1L, 
1L, 1L), `AC-E4` = c(0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 
0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L), 
    `AC-G15` = c(0L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 1L, 1L, 0L, 
    1L, 1L, 0L, 1L, 1L, 1L, 0L, 1L, 0L, 1L, 1L, 1L, 1L, 1L), 
    `AC-E15` = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L), 
    `SC-G4` = c(0L, 1L, 1L, 0L, 1L, 1L, 1L, 0L, 0L, 1L, 0L, 1L, 
    1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L), `SC-E4` = c(0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L), `SC-G9` = c(0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L), `SC-E9` = c(0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 1L, 0L, 0L, 0L, 0L)), row.names = c("0", "1", "2", 
"3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", 
"15", "16", "17", "18", "19", "20", "21", "22", "23", "24"), class = "data.frame")`

**Comment by bagcik1lumc** [comment]
`  KM-G4 KM-E4 KM-G15 KM-E15 AC-G4 AC-E4 AC-G15 AC-E15 SC-G4 SC-E4 SC-G9 SC-E9
0     0     0      0      0     0     0      0      0     0     0     0     0
1     1     0      1      0     1     0      1      0     1     0     0     0
2     0     0      0      0     1     0      1      0     1     0     0     0
3     0     1      0      0     1     1      1      0     0     0     0     0
4     0     0      0      0     1     0      1      0     1     0     0     0
5     0     0      0      0     1     0      1      0     1     0     0     0
6     0     0      0      0     1     0      1      0     1     0     0     0
7     0     0      0      0     0     1      0      0     0     0     0     0
8     0     1      0      0     1     1      1      0     0     1     0     0
9     0     0      0      0     1     0      1      0     1     0     0     0`

**Comment by krassowski** [comment]
The provided data is insufficient I am unable to help here without a self contained example; it is not clear why

> "0"s should also be part of the intersection

since zero by definition indicates that an observation is NOT in the intersection.

If anyone is struggling with obtaining desired result please open a new issue providing sufficient detail and description.
