### ISSUE TITLE
sort intersections by degree?

### ISSUE THREAD

**Issue by taylorreiter** [krassowski/complex-upset#18]
Is it possible to sort intersections by degree? I would like to be able to sort the intersections with the highest degree first (e.g., have the intersection shared between the most number of sets come first). This is possible with in the UpSetR package with `UpSetR::upset(order.by = "degree")`

**Comment by krassowski** [comment]
Thank you for bringing this up. I planned to add customization of the sort for some time, and just got to implenet it now. After updating the package with:

```
devtools::install_github("krassowski/complex-upset")
```

it will be possible to specify `sort_intersections_by` argument:

```
upset(movies, genres, sort_intersections_by='degree')
```

**Comment by taylorreiter** [comment]
Thank you so much!! My upset plots are now as beautiful as I could ever wish!
