### ISSUE TITLE
y axis units for the intersection size and stacking plots

### ISSUE THREAD

**Issue by evesilk** [krassowski/complex-upset#186]
**Objective**
I have two pleas for help: 

1) Is there a way to change the y axis unit from number (size), to proportion / percentage (i.e. to show prevalence where the numerator is the set size and the denominator is the total dataset)?

2) Is there a way to stack the different intersection modes on top of each other? For example, to stack Inclusive intersection size on top of the plot showing exclusive intersection size?

Many thanks indeed.

**Comment by krassowski** [comment]
Yes and yes.
1. See https://krassowski.github.io/complex-upset/articles/Examples_R.html#display-percentages
2. See https://krassowski.github.io/complex-upset/articles/Examples_R.html#showing-intersection-sizeunion-size-ratio - you can use multiple `intersection_size()`

**Comment by krassowski** [comment]
Closing as answered, please reopen with more details (code that you tried) if the links above did not lead you to a solution.

**Comment by evesilk** [comment]
Thank you! No. 1 worked well!


No.2 i'm still struggling to find a way around. 

I would like to produce something like the figure below, but show inclusive intersection size (e.g. bar in pink) with  the added exclusive intersection size (e.g. bar in turquoise) stacked above (i.e. bars stacked on the same plot instead of on two plots stacked). Something like this: 

<img width="814" alt="Screenshot 2023-09-23 at 00 15 05" src="https://github.com/krassowski/complex-upset/assets/145388803/d48f8458-30b3-4e7e-9f47-f5acb77c3721">

Is this possible?

**Comment by krassowski** [comment]
No, not easily.

**Comment by evesilk** [comment]
It seems _potentially_ possible using "+ scale_fill_venn_mix ()" (from here: https://krassowski.github.io/complex-upset/articles/Examples_R.html#region-selection-modes) 

<img width="797" alt="Screenshot 2023-09-23 at 16 40 32" src="https://github.com/krassowski/complex-upset/assets/145388803/0c0af327-fa89-4bc3-a65b-7db4cd3b32f7">

The difference for the example here being that it seems you have to select the colour for each of the variables?  

Visually, I think it could be incredibly useful to be able to plot the exclusive intersection and either inclusive intersection or union on a stacked bar, to more easily visualise this ratio. Would a the specific new function on R for this do the job? 

Thanks

**Comment by krassowski** [comment]
I think that stacking them would be misleading because the intersection would look to be larger than it actually is. I can imagine having them side-by-side rather than stacked.

**Comment by evesilk** [comment]
Ah yes I see. Side by side could helpful....
Unless there's a way of showing the inclusive intersection bars with a line to stratify them by exclusive intersection and the 'extra' inclusive intersection number? i.e. similar to the plot above showing how each bar is stratified by mpaa, but instead of mpaa, by inclusive / exclusive intersection size???
