### ISSUE TITLE
Missing 'x' argument in gsub

### ISSUE THREAD

**Issue by HJones666** [krassowski/complex-upset#19]
Hello,
First of all great package, I really like the extensibility of it !
I have discovered that the 'x' parameter in the gsub function in names_of_true is missing, which causes an error if the colnames contain a '-' character. Reprex is below:
``` r
test_frame<-data.frame(
  a = c(TRUE, TRUE, TRUE),
  b = c(FALSE, FALSE, FALSE),
  c = c(TRUE, FALSE, TRUE)
)

colnames(test_frame) <- c("a","b","C-")
apply(test_frame, 1, ComplexUpset::names_of_true)
#> Error in gsub("-", "_"): argument "x" is missing, with no default

#add name as 'x' parameter for gsub
names_of_true2<-function (row) 
{
  sanitized_names = c()
  for (name in names(which(row))) {
    if (grepl("-", name, fixed = TRUE)) {
      name = gsub("-", "_",name)
      if (name %in% names(which(row))) {
        stop("The group names contain a combination of minus characters (-) which could not be simplified; please remove those.")
      }
    }
    sanitized_names = c(sanitized_names, name)
  }
  paste(sanitized_names, collapse = "-")
}

apply(test_frame, 1, names_of_true2)
#> [1] "a-C_" "a"    "a-C_"
```

<sup>Created on 2020-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Additionally I was wondering what the reason was for using a for loop in this function as grepl and gsub support vector inputs, removing the for loop could have significant performance gains especially for very 'wide' data

``` r
#test_data 10 obs 4000 variables
test_data <-data.frame(replicate(4000,sample(c(TRUE,FALSE),10,rep=TRUE)))

#Simple mock-up
names_of_true3<-function (row)
{
  true_row_names <- names(which(row))
  fixed_row_names <- gsub("-","_",true_row_names)
  if(any(grepl("-",fixed_row_names, fixed = TRUE))) {stop("- detected")}
  
  paste(fixed_row_names, collapse = "-")
}

bench::mark(
  apply(test_data, 1, names_of_true3),
  apply(test_data, 1, ComplexUpset::names_of_true)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 x 6
#>   expression                                           min  median `itr/sec`
#>   <bch:expr>                                       <bch:t> <bch:t>     <dbl>
#> 1 apply(test_data, 1, names_of_true3)               24.4ms  27.2ms     37.0 
#> 2 apply(test_data, 1, ComplexUpset::names_of_true) 124.1ms 129.8ms      7.76
#> # ... with 2 more variables: mem_alloc <bch:byt>, `gc/sec` <dbl>
```

<sup>Created on 2020-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krassowski** [comment]
Thank you for your insight! Would you like to create a pull request with your improvements?

**Comment by HJones666** [comment]
Sure, I'll put one together

**Comment by krassowski** [comment]
Actually, your `names_of_true3` will not protect a user who has a data.frame with columns named: `c('a-b', a_b')` from a distortion of the data (which is what I aimed for). Either way, I agree that there is a bug with `x` missing in `gsub`, and that this function can be optimized up in a way or two.

**Comment by HJones666** [comment]
I see what you mean, perhaps then the easiest solution is check for '-' and then check for duplicated names and then repair as necessary. I'll put something together tomorrow

**Comment by krassowski** [comment]
I have fixed the issue with a missing argument for names and added tests, but you are very welcome to contribute a better implementation of this function. I hope that the addition of the tests will make it easier to contribute. Any questions - let me know.
