### ISSUE TITLE
Error message when running GitHub R example of ComplexUpset

### ISSUE THREAD

**Issue by sfd99** [krassowski/complex-upset#20]
**_Hi Mike,_** 

ComplexUpset is GREAT! .

**A quick question...**

...when I run your R code movies example,
 in link: 
      https://github.com/krassowski/complex-upset#showcase
(the example R source code _just under_ the nice upset plot!...),

I get this error message:

[1]  "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance"
Error in stack.data.frame(data, intersect) : no vector columns were selected**

_Yet,_
   ggplot2movies, beeswarm,  etc. 
   +all required pkgs are loaded ok...

Help! what am I missing?
**sfd99
San Francisco
Ubuntu Linux 18.04, 
latest versions of Rstudio and R.**

**Comment by krassowski** [comment]
Hi, thanks for trying out the package and opening an issue. While I cannot recreate this error (I just run the exact same code and it worked), it sounds like an issue with the second argument (which should be a character vector with names of columns from the data frame which is the first argument).

Did you exactly copy-paste the code from the example?

**Comment by krassowski** [comment]
If you would like to start with a simpler example (which may help to diagnose the issue), please try this one: https://rpubs.com/krassowski/minimal-demo-complex-upset

**Comment by sfd99** [comment]
Hi Mike,

Yes, (carefully) copied and pasted
the example in my Rstudio...

Let me paste below,
*exactly* what I copied (and run):

library(ggplot2)
library(ComplexUpset)
library(beeswarm)

if(!require(ggplot2movies)) install.packages('ggplot2movies')movies =
ggplot2movies::moviesgenres = c('Action', 'Animation', 'Comedy',
'Drama', 'Documentary', 'Romance')
# also tried enclosing the 6 categs above in double-quotes but = error msg.
upset(
    movies,
    genres,
    annotations = list(
        'Length'=list(
            aes=aes(x=intersection, y=length),
            geom=geom_boxplot()
        ),
        'Rating'=list(
            aes=aes(x=intersection, y=rating),
            geom=list(
                # if you do not want to install ggbeeswarm, you can
use geom_jitter
                ggbeeswarm::geom_quasirandom(aes(color=log10(votes))),
                geom_violin(width=1.1, alpha=0.5)
            )
        )
    ),
    queries=list(
        upset_query(
            intersect=c('Drama', 'Comedy'),
            color='red',
            fill='red',
            only_components=c('intersections_matrix', 'Intersection size')
        ),
        upset_query(
            set='Drama',
            fill='blue'
        ),
        upset_query(
            intersect=c('Romance', 'Drama'),
            fill='yellow',
            only_components=c('Length')
        )
    ),
    min_size=10,
    width_ratio=0.1
)



RAY
*calintel*@gmail.com
*SF*

**Comment by krassowski** [comment]
The lines breaks for:

**Comment by krassowski** [comment]
The line breaks for:

```
if(!require(ggplot2movies)) install.packages('ggplot2movies')movies =
ggplot2movies::moviesgenres = c('Action', 'Animation', 'Comedy',
'Drama', 'Documentary', 'Romance')
```

appear distorted. It should be:

```
if(!require(ggplot2movies)) install.packages('ggplot2movies')
movies = ggplot2movies::movies
genres = c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance')
```

**Comment by sfd99** [comment]
*Hi Mike,*

Tried the simpler example,
as suggested,
but get exactly the same error...

> upset(+     movies, genres,+     base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),+     min_size=100,+     width_ratio=0.1+ )[1] "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance"Error in stack.data.frame(data, intersect) :
  no vector columns were selected

>

RAY
*calintel*@gmail.com
SF
---

**Comment by krassowski** [comment]
Have you tired in a clean R session, e.g. from R console? I would really like to help you, but cannot pin down why it works for me, but not for you. I tried to reproduce this in RStudio, but it works ok for me. Please see the gif that I recorded below:

![works_for_me](https://user-images.githubusercontent.com/5832902/78068790-f1f3e800-7390-11ea-824a-67b77d323c5a.gif)

Do you see anything different in your environment? My R version is:

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

**Comment by sfd99** [comment]
Yes, its:
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

Weird...the movies df
and all req. pkgs are loaded correctly.

> class(genres)[1] "character"> genres[1] "Action"      "Animation"
[3] "Comedy"      "Drama"
[5] "Documentary" "Romance"

>

RAY
*calintel*@gmail.com
SF
---

**Comment by krassowski** [comment]
I will have a look using 3.6.3 later, though I would not expect an issue there. Apologies that it does not work as intended and thank you for providing the detailed information - this is really appreciated!

**Comment by sfd99** [comment]
_Don't  worry Mike!._

I'll try several things here
and will let you know in this thread
if I find any culprit.

As usual,
it could be an insignificant detail on my side!. :-)

Will let you know!.

**Comment by krassowski** [comment]
Hi @sfd99,

I have overhauled the exports from the package and applied more stringent quality checks, including automated testing on three R versions. Would you mind installing the new version with:

```R
if(!require(devtools)) install.packages("devtools")
devtools::install_github("krassowski/complex-upset")
```

and checking if it works for you now?

**Comment by sfd99** [comment]
Hi Mike,

UNinstalled prev version of ComplexUpset
and installed latest version (ver 0.5.0), with:
  devtools::install_github("krassowski/complex-upset")

I tried the "MINIMAL R DEMO EXAMPLE":
    https://rpubs.com/krassowski/minimal-demo-complex-upset

Output:
 (in either Rstudio  or also in "pure" R 3.6.3 without Rstudio)
=====
> library(ggplot2movies)
> library(ComplexUpset)
> head(movies)
# A tibble: 6 x 24
  title                     year length budget rating
  <chr>                    <int>  <int>  <int>  <dbl>
1 $                         1971    121     NA    6.4
2 $1000 a Touchdown         1939     71     NA    6  
3 $21 a Day Once a Month    1941      7     NA    8.2
4 $40,000                   1996     70     NA    8.2
5 $50,000 Climax Show, The  1975     71     NA    3.4
6 $pent                     2000     91     NA    4.3
  votes    r1    r2    r3    r4    r5    r6    r7    r8
  <int> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1   348   4.5   4.5   4.5   4.5  14.5  24.5  24.5  14.5
2    20   0    14.5   4.5  24.5  14.5  14.5  14.5   4.5
3     5   0     0     0     0     0    24.5   0    44.5
4     6  14.5   0     0     0     0     0     0     0  
5    17  24.5   4.5   0    14.5  14.5   4.5   0     0  
6    45   4.5   4.5   4.5  14.5  14.5  14.5   4.5   4.5
     r9   r10 mpaa  Action Animation Comedy Drama
  <dbl> <dbl> <chr>  <int>     <int>  <int> <int>
1   4.5   4.5 ""         0         0      1     1
2   4.5  14.5 ""         0         0      1     0
3  24.5  24.5 ""         0         1      0     0
4  34.5  45.5 ""         0         0      1     0
5   0    24.5 ""         0         0      0     0
6  14.5  14.5 ""         0         0      0     1
  Documentary Romance Short
        <int>   <int> <int>
1           0       0     0
2           0       0     0
3           0       0     1
4           0       0     0
5           0       0     0
6           0       0     0
> genres = c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short')
> upset(
+     movies, genres,
+     base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),
+     min_size=100,
+     width_ratio=0.1
+ )
[1] "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance, Short"
Error in stack.data.frame(data, intersect) : 
  no vector columns were selected
> 
so, same error message...

Now, time for a supposition:
do you think that maybe
some other preloaded  pkg/s
might be interfering?.

Here's a list of loaded pkgs in my Rstudio:

> (.packages()) 
 [1] "ggplot2"        [2] "ComplexUpset"   [3] "ggplot2movies"  [4] "stats"          [5] "graphics"       [6] "grDevices"      [7] "utils"          [8] "datasets"       [9] "methods"       [10] "base"
--

Again, the same error appears outside Rstudio,
ie, just using a "pure" R window...
in Ubuntu Linux 18.04, latest Rstudio and R 3.6.3.

A real mystery... :-)

**Comment by gofraidh** [comment]
Hi, I can (unfortunately) confirm I am having the same issue. I though it might because I have installed the package from a local file (unfortunately, one of the computers I am using is a University laptop which seems to block how it installs remote packages); however, it is the same error.

I'll describe what's happening to me as well:

#### Session
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    packrat_0.5.0
``` 
#### Installing package
```
remotes::install_local(path = "C:/Users/Martin/Downloads/complex-upset-master.zip", 
                       dependencies = c( "Depends", "Imports", "LinkingTo", "Suggests", "Enhances"),
                       upgrade = "always")
```
#### Packages
```
> packageVersion("ggplot2movies")
[1] ‘0.0.1’
> packageVersion("ComplexUpset")
[1] ‘0.5.0’
> packageVersion("ggplot2")
[1] ‘3.3.0’

> (.packages())
 [1] "ggplot2"       "ComplexUpset"  "ggplot2movies" "stats"        
 [5] "graphics"      "grDevices"     "utils"         "datasets"     
 [9] "methods"       "base"
```

#### Running the minimal reproducible example
```
library(ComplexUpset)
library(ggplot2)
movies <- ggplot2movies::movies
head(movies)
genres <- c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short')

upset(
  movies, genres,
  base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),
  min_size=100,
  width_ratio=0.1
)
```
#### Result
```
[1] "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance, Short"
Error in stack.data.frame(data, intersect) : 
    no vector columns were selected
```

**Comment by krassowski** [comment]
Hi @gofraidh, thank you for your comment.

I managed to get a similar message today with:

```R
df = data.frame(
    a=c(TRUE, FALSE),
    b=c(TRUE, TRUE),
    c=c(FALSE, TRUE),
    d=c(FALSE, FALSE)
)

upset_data(df, c('a', 'b', 'c', 'd'), min_size=2)
```

> [1] "Dropping empty groups: a, b, c, d"
> Error in stack.data.frame(data, intersect) : 
>   no vector columns were selected

<details>
This is different from not having columns:

```R
df = data.frame()

upset_data(df, c('a', 'b', 'c', 'd'))
```

> Error in `[.data.frame`(data, , intersect) : undefined columns selected
</details>

I also confirmed that this is NOT an issue with R 3.6.3 (I upgraded and tested with this version).

Thank you for all the help in narrowing down this issue.

**Comment by krassowski** [comment]
I got it! I had an older version of tibble, and tibble changed how it behaves for subseting.
@sfd99 @gofraidh would you mind trying out this:

```R
library(ComplexUpset)
library(ggplot2)
# added as.data.frame:
movies <- as.data.frame(ggplot2movies::movies)
head(movies)
genres <- c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short')

upset(
  movies, genres,
  base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),
  min_size=100,
  width_ratio=0.1
)
```

**Comment by krassowski** [comment]
Now fixed, by converting tibbles do data frames internally. Please update the package (to 0.5.2) and let me know if everything works for you.

**Comment by sfd99** [comment]
**_Mike -_**
the new **version 0.5.2** 
works great now!.

It was a mystery...
I imagine you got some hints
from the great **Inspector Morse** and **Inspector Lewis** 
form the Oxford PD ?.  :-)
https://www.pbssocal.org/drama/inspector-morse-preview/

**Comment by sfd99** [comment]
Update - 
ok,  to get readable "Set size" # values.
I changed to:
...width_ratio=0.3 in upset().

Looking better all the time!.

**Comment by sfd99** [comment]
Mike -
  you have done a fantastic job
with this pkg!.
Dynamite!  (in the good sense of course...).

I am now going through the great, clear examples
in page:
https://krassowski.github.io/complex-upset/articles/Examples_R.html#4-adjusting-set-size-

**Comment by gofraidh** [comment]
#### Version 0.5.2

#### After update -  Data ARE converted to data.frame object with as.data.frame()

```
library(ComplexUpset)
library(ggplot2)
#added as.data.frame:
movies <- as.data.frame(ggplot2movies::movies)
head(movies)
genres <- c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short')

#Example
upset(
  data =  movies, 
  intersect = genres,
  base_annotations = list('Intersection size' = intersection_size(counts = FALSE)),
  min_size = 100,
  width_ratio = 0.1
)

[1] "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance, Short"
# Output is plot.
```

#### After update - Data ARE NOT converted to data.frame object with as.data.frame()

```
library(ComplexUpset)
library(ggplot2)
movies <- ggplot2movies::movies
head(movies)
genres <- c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short')

# Example
upset(
  data =  movies, 
  intersect = genres,
  base_annotations = list('Intersection size' = intersection_size(counts = FALSE)),
  min_size = 100,
  width_ratio = 0.1
)

[1] "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance, Short"
# Output is plot.
```

#### After update - Data ARE converted to tibble object with as_tibble()
```
library(ComplexUpset)
library(ggplot2)
library(tibble)
movies <- as_tibble((ggplot2movies::movies))
head(movies)
genres <- c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short')

# Example
upset(
  data =  movies, 
  intersect = genres,
  base_annotations = list('Intersection size' = intersection_size(counts = FALSE)),
  min_size = 100,
  width_ratio = 0.1
)

[1] "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance, Short"
# Output is plot.
```

```
sessionInfo()

R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
  [1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] tibble_3.0.0       ggplot2_3.3.0      ComplexUpset_0.5.2

loaded via a namespace (and not attached):
  [1] Rcpp_1.0.4          rstudioapi_0.11     magrittr_1.5       
[4] tidyselect_1.0.0    munsell_0.5.0       colorspace_1.4-1   
[7] R6_2.4.1            rlang_0.4.5         fansi_0.4.1        
[10] dplyr_0.8.5         patchwork_1.0.0     tools_3.6.3        
[13] ggplot2movies_0.0.1 grid_3.6.3          gtable_0.3.0       
[16] utf8_1.1.4          cli_2.0.2           withr_2.1.2        
[19] ellipsis_0.3.0      digest_0.6.25       assertthat_0.2.1   
[22] lifecycle_0.2.0     crayon_1.3.4        farver_2.0.3       
[25] purrr_0.3.3         vctrs_0.2.4         glue_1.4.0         
[28] labeling_0.3        compiler_3.6.3      pillar_1.4.3       
[31] scales_1.1.0        pkgconfig_2.0.3    
```

I confirm it works fine now. Thank you for providing the fix and your hard work on the package.

*Minor note: One thing that I find (personally) confusing (and this unfortunately also applied to the "original" UpSetR package) is that the function doesn't "behave" as other ggplot extensions. For example, I'd expect the function to accept a long format of data; however, wide format is supplied which is feels a bit unggplot in my opinion. Therefore; the below example does not work. (I don't know if ggupset handles this and behaves as a ggplot2 extension - I'd expect so given it is named like this.) This is not intended as a critique and I know it isn't related to the bug described here. Thank you for your work on this package!*

#### Example: Testing long data format
```
library(ComplexUpset)
library(ggplot2)
library(tidyverse)
movies <- (ggplot2movies::movies)
head(movies)

# Testing long format with tidyverse approach
movies_long <- movies %>%
  pivot_longer(cols = Action:Short, names_to = "Genre", values_to = "Genre_TRUE_FALSE")

# Example
upset(
  data = movies_long, 
  intersect = Genre,
  base_annotations = list('Intersection size' = intersection_size(counts = FALSE)),
  min_size = 100,
  width_ratio = 0.1
)

Error in unlist(intersect) : object 'Genre' not found
# Output is the error above.
```

**Comment by krassowski** [comment]
Thank you for confirming that the new version works @gofraidh. I have opened another issue to remember about the need to improve the user experience with respect to the long format data frames.
