### ISSUE TITLE
Selecting only specific degrees of intersection

### ISSUE THREAD

**Issue by jbp7** [krassowski/complex-upset#22]
Is there a way to selectively display only intersections with degree <= 2  or something similar to `nintersects` in UpsetR?

**Comment by jbp7** [comment]
I figured it out by subsetting the input data to rowSums() <= 2

**Comment by krassowski** [comment]
Thank you for opening this issue. I hope you find this package helpful. I will add an option for the minimal and maximal degree of intersections today.

**Comment by krassowski** [comment]
I added `min_degree` and `max_degree` arguments.

**Comment by jbp7** [comment]
Great, thanks!
