### ISSUE TITLE
Add an example showing how to display counts on "Set size"s

### ISSUE THREAD

**Issue by krassowski** [krassowski/complex-upset#24]
Based on the suggestion from https://github.com/krassowski/complex-upset/issues/23#issuecomment-609092179 by @sfd99.

One quick solution:
```R
upset(
    movies, genres,
    min_size=10,
    set_sizes=upset_set_size(
        geom=function(...) {
            list(
                geom_bar(...),
                geom_text(..., aes(label=..count..))
            )
        },
        stat='count'
    )
)
```

but I will also consider:
- adding a dedicated helper function
- a new parameter to `upset_set_size`
- and other possible ways of achieving that without modifying the package

**Comment by sfd99** [comment]
_Yes!_ 

A dedicated helper function 
for counts of the horizontal bars 
of **Set Size**
would certainly help A LOT!.

Using the temp solution
(as described above),
does show the number values for each **Set size** horiz bar.

But right now,
(usinf this temp solution)
shows hard to read numbers,
because these # values(colored black),
 overlap (black-on-black!),
with the black Set size bars...

So hard to read these numbers...

Maybe also function 
to change the color of the Set size horiz bars 
to light gray?.

That way, the count #s (in black),
would be readable, 
_even if_ they overlap with the gray horiz. bars!... :-)

**Comment by HelloWorldLTY** [comment]
Hi, my understanding of this feature is to display the count value of each set. However, this solution does not work for me.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/43333475/226370060-56b1b60d-9b49-44fb-9f27-906e22b97b84.png">
I meet an error here.

**Comment by sfd99** [comment]
**_Hi HelloWorldLTY ,_**

thanks for reporting an error.

But,
could you please be _more specific_?.
for example:

**1)** 
what is the exact and complete R code 
that gives you this error,

**2)** 
what is the _exact Error message_
you are receiving?.

**3)**  
which _version_ of software 
   (R / Rstudio, etc.) 
and 
    the _version_ of the COMPLEX-UPSET package 
are you are using?.

**4)** 
which  Operating System
are you running? 
(Linux, Windows, MacOS...) ?.

These additional 
and complete details,
will _certainly help_ the Author 
of this wonderful software
investigate and answer your question...

_Thanks!_
**SFd99
San Francisco**

**Comment by leppott** [comment]
Same troubles as @HelloWorldLTY 

**Code**

```
 library(ComplexUpset)
    library(ggplot2)
    
    movies <- read.csv(system.file("extdata", "movies.csv", package = "UpSetR"), 
                                           header = T, sep = ";")
    genres <- names(movies)[3:19]
    
    upset(
      movies, genres,
      min_size=10,
      set_sizes=upset_set_size(
        geom=function(...) {
          list(
            geom_bar(...),
            geom_text(..., aes(label=..count..))
          )
        },
        stat='count'
      )
    )
```

**Error**
![image](https://user-images.githubusercontent.com/24276278/231887638-c11231be-77a5-466e-b347-8acc43d7a37b.png)

**Session Info**
![image](https://user-images.githubusercontent.com/24276278/231887753-83ab4e4f-1526-4995-9709-a41b11c86e4c.png)
