### ISSUE TITLE
Add an example how to change bar/point color in interaction size/matrix

### ISSUE THREAD

**Issue by JegorG** [krassowski/complex-upset#27]
Thanks for the great package! I read through the whole example documentation. I understand how to change color of all bars in set size but I don't understand how to make any color change for interaction size and matrix.

Do I need to pass each interaction to an upset query?

**Comment by krassowski** [comment]
Thank you for opening this issue. If you want to change colour of individual points/sets then queries are the way to go, but if you want to change colour of everything, then there are better ways. I can have a look at it tonight if you mind explaining in a bit more detail (e.g. you could provide a sketch of what you would like to achieve).

**Comment by JegorG** [comment]
Indeed I am trying to change everything, for example, that all bars are red in the interaction size and all points are blue. (Maybe it's even possible to change linetype/color?)

Something like 
=upset_set_size(
   geom=geom_point,
    stat='count',
            color='blue')

but instead _upset_interaction_size()_, is what I was hoping to find.

Let me know if a sketch is still needed

**Comment by krassowski** [comment]
Sorry for a delay here - I will refactor `intersection_size` helper soon, in the meantime you can use:

```R
upset(
    movies, genres,
    min_size=10,
    base_annotations=list(
        'Intersection size'=upset_annotate(
            '..count..',
            geom_bar(fill='blue')
        )
    )
)

```R
upset(
    movies, genres,
    min_size=10,
    base_annotations=list(
        'Intersection size'=intersection_size(
            counts=FALSE,
            aes=aes(fill='bars_color')
        )
    )
) & scale_fill_manual(values=c('bars_color'='blue'), guide='none')
```

**Comment by JegorG** [comment]
Thanks!

**Comment by krassowski** [comment]
It is slightly easier now, see https://github.com/krassowski/complex-upset/issues/67#issuecomment-738345006 (and the relevant section of the documentation).
