### ISSUE TITLE
custom titles

### ISSUE THREAD

**Issue by alexeilutay** [krassowski/complex-upset#30]
I can't find a way to change the words "Intersection size" at the y-axis. Would be great to have an option to set all the titles manually, same as in ggplot. Or if I am blind, please show me the way.
Thank you in advance

**Comment by krassowski** [comment]
Like this?

```R
upset(
    movies, genres,
    min_size=100,
    base_annotations=list(
        'Your text'=intersection_size()
    )
)
```

![image](https://user-images.githubusercontent.com/5832902/81068649-9d381580-8ed8-11ea-86af-5216f72a0372.png)

**Comment by alexeilutay** [comment]
Oh! That was in the example, I was really confused that the text is the same as the object.
 Thank you.
