### ISSUE TITLE
Highlight multiple intersections

### ISSUE THREAD

**Issue by eds-slim** [krassowski/complex-upset#33]
Thanks for the great package. Is it possible to highlight / query multiple intersections in the intersection matrix using different color?

If I update the example from the doc, using
```
...
queries=list(
    upset_query(
      intersect=c('Drama', 'Comedy'),
      color='red',
      fill='red',
      only_components=c('intersections_matrix')
    ),
    upset_query(
      intersect=c('Romance', 'Drama'),
      color='yellow',
      only_components=c('intersections_matrix')
    )
  )
...
```
I receive the error
```
Error: Aesthetics must be either length 1 or the same as the data (4): colour
```

Thanks.

**Comment by krassowski** [comment]
Thank you. I got it, needs a tiny change to fix it - will be there in 20 minutes.

**Comment by krassowski** [comment]
The potential fix has been just published as v0.5.11 - you can update the package using:

```
devtools::install_github("krassowski/complex-upset")
```

Please let me know if the fix works for you. And again, thanks for highlighting this!

**Comment by krassowski** [comment]
I am closing this issue now as [all the tests passed](https://travis-ci.org/github/krassowski/complex-upset/builds/696424076), but your feedback is still very welcome.

**Comment by eds-slim** [comment]
Thanks, it works as long as the same aesthetics are passed to each intersection query, i.e.
```
queries=list(
    upset_query(
      intersect=c('Drama', 'Comedy'),
      color='red',
      fill = 'red',
      only_components=c('intersections_matrix')
    )
    , upset_query(
      intersect=c('Romance', 'Drama'),
      color='yellow',
      fill='yellow',
      only_components=c('intersections_matrix')
    )
  )
```
works, but omitting either `fill='yellow' or `color='yellow'` from the second query gives the error `Error: Unknown colour name: NULL`. 

I'm quite happy with specifiying the same set of aes's for ech query.

**Comment by krassowski** [comment]
Thank you for testing the update. I re-created the reported issue and fixed it in v0.5.12. Huge thanks again, and please do let me know of any other issues you may find.

**Comment by dence** [comment]
Hi I'm encountering what I think is a related issue. At least, it has to do with specifying upset_queries and getting the "Aesthetics must be length 1 or ..." error from ggplot. I'm trying to specify multiple upset queries with different colors, but there's a point where I added another upset plot with a different color, I start getting that error. 

I'm attaching two scripts and the data file to use with the script. The only difference that I can see between the scripts is that I'm specifying a different color and fill for the first upset_query. 

I've tried installing the latest version from github and still got the same error. 

[Archive.zip](https://github.com/krassowski/complex-upset/files/6946907/Archive.zip)


Thank you for your help.

**Comment by krassowski** [comment]
Hi @dence this is really a lot of code and data in the archive you provided. Could you create a minimal reproducible example please? This would help me to helpy you quickly.

**Comment by dence** [comment]
Hi, Here is a minimal script that replicates the error. When I change the color in the last upset_query (the one with "plant1") from "red" to "blue", I get the aesthetics error.

[binary_DEGs.upsetplot.doesnt_work.R.zip](https://github.com/krassowski/complex-upset/files/6947019/binary_DEGs.upsetplot.doesnt_work.R.zip)

**Comment by dence** [comment]
Actually, after playing around with this some more, I think this might be a case of just a very unhelpful error message. I think the error occurs when any of the specified intersections are empty.

**Comment by krassowski** [comment]
Thank you for getting back to me. Sorry I did not have time earlier. Unhelpful messages are bad! I fully agree that this is something that should be fixed. Can you reproduce this with the `movies` example from the readme?

**Comment by dence** [comment]
Yes, I'll try to get to that this week. Do you want just the R script or would there be some sort of printout or log that would be helpful for you?

**Comment by krassowski** [comment]
Just the code that triggers it would be perfect.

**Comment by dence** [comment]
[](url)Hi, I'm attaching two scripts called annoying_errors.works.R and annoying_errors.doesnt_work.R. The I try to plot theplot in the Rstudio console, I get this error. 
-----------
Error: Aesthetics must be either length 1 or the same as the data (2): colour and fill
Run `rlang::last_error()` to see where the error occur
-----------

[Archive.zip](https://github.com/krassowski/complex-upset/files/6971751/Archive.zip)
red.

**Comment by Scott-Coggeshall** [comment]
I'm running into this issue as well. It's popping up in a situation where I want to create the same upset plot for multiple subsets of my data. In some subsets, certain intersections become empty. Is there a way around this issue, other than manually adjusting the queries for each subset?
