### ISSUE TITLE
Remove legend to geom_bar

### ISSUE THREAD

**Issue by cristobalcar** [krassowski/complex-upset#39]
Hi, how to remove legend from geom_bar??

**Comment by krassowski** [comment]
Hi @cristobalcar. There are many ways to hide the legend in ggplot, e.g. by passing `guide=False` to the geom of your choice, or by using `guides()` to disable specific legends. Please provide a minimal reproducible example/circumstance in which you are struggling to hide the legend.

**Comment by cristobalcar** [comment]
I tried with theme and guides... I think I'm not applying it correctly.

This is the code:
```
'LETALIDAD'=list(
  aes=aes(x=intersection, fill=FALLECIDOS)
  ,geom=list(
    geom_bar(stat='count', position='fill')
    ,labs(fill = "")
    ,guides(FALLECIDOS='none')
    ,geom_text(
      aes(label=paste(round(100*..count../tapply(..count.., ..x.., sum)[..x..]), '%', sep='')
          ,color=ifelse(FALLECIDOS=='FALLECIDO', 'show', 'hide'))
      ,stat='count'
      ,position=position_fill(vjust = 0.5)
      ,size=3)
    ,scale_color_manual(values=c('show'='black', 'hide'='transparent'), guide=FALSE)
    ,scale_fill_manual(values=as.vector(c(GRIS,ROJO)))
    ,scale_y_continuous(n.breaks = 3
                        ,labels=scales::percent_format())))
```
This is the output:
<img width="1514" alt="Screen Shot 2020-06-14 at 21 38 18" src="https://user-images.githubusercontent.com/29803674/84610081-6a921d00-ae87-11ea-9bbe-74c914bee6f6.png">

**Comment by krassowski** [comment]
You also need to add `guide=FALSE` to `scale_fill_manual()`, see:

```R
upset(
    movies, genres, name='genre', width_ratio=0.1, min_size=100,
    base_annotations=list(
        'MPAA Raiting'=list(
            aes=aes(x=intersection, fill=mpaa),
            geom=list(
                geom_bar(stat='count', position='fill'),
                scale_fill_manual(values=c(
                    'R'='#E41A1C', 'PG'='#377EB8',
                    'PG-13'='#4DAF4A', 'NC-17'='#FF7F00'
                ), guide=FALSE)   # <------- like here
            )
        )
    )
)
```

![image](https://user-images.githubusercontent.com/5832902/84610642-2caaee00-aeb3-11ea-8408-eb883f6a0fc9.png)

**Comment by cristobalcar** [comment]
it worked perfectly!
Thanks again
