### ISSUE TITLE
Put a geom_text related to the max intersection

### ISSUE THREAD

**Issue by cristobalcar** [krassowski/complex-upset#40]
Hi, I wanted to know how to situate a geom_text related to the max intersection of the plot.
Code:
```
'EDAD'=list(
  aes=aes(x=intersection, y=EDAD)
  ,geom=list(geom_boxplot()
             ,geom_hline(aes(yintercept = median(EDAD))
                         ,color='coral'
                         ,linetype="dashed")
             ,geom_text(aes(max(intersection),median(EDAD),label = round(median(EDAD),1), vjust = -1))
  )
)
```
Output:
It locates in the red circle, and wanted to situate it in the red arrow.
<img width="1522" alt="Screen Shot 2020-06-15 at 12 35 55" src="https://user-images.githubusercontent.com/29803674/84683611-791f1980-af05-11ea-90db-8c8aa5e0d4b7.png">

**Comment by krassowski** [comment]
I would need an miminal working example to understand this better. Could you please modify the movies example to showcase what you are trying to achieve, please?

**Comment by cristobalcar** [comment]
The idea is to put the median label in the last interception to the right

```
upset(
  movies, genres, name='genre', width_ratio=0.1, min_size=100,
  base_annotations=list(
    'YEAR'=list(
      aes=aes(x=intersection, y=year),
      geom=list(
        geom_boxplot()
        ,geom_hline(aes(yintercept = median(year))
                    ,color='coral'
                    ,linetype="dashed")
        ,geom_text(aes(max(intersection)
                       ,median(year)
                       ,label = round(median(year),1)
                       , vjust = -1
                       ,color="red"))
      )
    )
  )
)
```

**Comment by krassowski** [comment]
Two options:

#### 1. Set `x = 'Drama-Romance'`

This requires adjustment each time you change the order of intersections.

![image](https://user-images.githubusercontent.com/5832902/84708626-c24c8900-af58-11ea-88ca-023b5cd6a643.png)

<details>
<summary>Code</summary>

```R
upset(
    movies, genres, name='genre', width_ratio=0.1, min_size=100,
    base_annotations=list(
        'Year'=list(
            aes=aes(x=intersection, y=year),
            geom=list(
                geom_boxplot(),
                geom_hline(
                    aes(yintercept = median(year)),
                    color='coral',
                    linetype="dashed"
                ),
                geom_text(
                    aes(
                        y = median(year),
                        label = round(median(year), 1)
                    ),
                    x = 'Drama-Romance',
                    vjust = -1,
                    color = "red",
                    check_overlap = TRUE
                )
            )
        )
    )
)
```

</details>

#### 2. Set `x = Inf, hjust=1`

This is not great for having this text centred on the last intersection, but possibly closer to what you wanted to achieve.

![image](https://user-images.githubusercontent.com/5832902/84708830-1c4d4e80-af59-11ea-97ef-8b8603c2fb04.png)

<details>
<summary>Code</summary>

```R
upset(
    movies, genres, name='genre', width_ratio=0.1, min_size=100,
    base_annotations=list(
        'Year'=list(
            aes=aes(x=intersection, y=year),
            geom=list(
                geom_boxplot(),
                geom_hline(
                    aes(yintercept = median(year)),
                    color='coral',
                    linetype="dashed"
                ),
                geom_text(
                    aes(
                        y = median(year),
                        label = round(median(year), 1)
                    ),
                    x = Inf,
                    vjust = -1,
                    hjust = 1,
                    color = "red",
                    check_overlap = TRUE
                )
            )
        )
    )
)
```

</details>

Also, either change the `geom_text` to `annotate` or use `check_overlap=TRUE` (as in examples above) to avoid repetitions of the text written on top of each other.

**Comment by cristobalcar** [comment]
Thank you, both worked with the movies data but the dynamic code with my data it returns this error:
Error in if (n > 0) c(NA_integer_, -n) else integer() : 
  argument is of length zero

**Comment by krassowski** [comment]
It might be a problem in your code. It would be only guessing without seeing it - sorry.
