### ISSUE TITLE
Highlight the empty intersection

### ISSUE THREAD

**Issue by arcresu** [krassowski/complex-upset#41]
Is it possible to highlight the "empty" intersection / complement (i.e. the intersection where all the binary variable are false)?

There is no problem plotting the empty intersection, but none of these hypothetical queries, work:
```R
upset_query(intersect = character(), fill='yellow')
upset_query(intersect = c(), fill='yellow')
upset_query(intersect = NA, fill='yellow')
```

**Comment by krassowski** [comment]
Thank you for opening this issue. Yes, this is an important function which was not available before. I have now implemented and documented it. For now, only passing `NA` will work but it might be possible to make the two former ideas work too. Here is an example:




![image](https://user-images.githubusercontent.com/5832902/84934910-e41c4c00-b0cf-11ea-87bf-8b1d501a71a3.png)

**Comment by krassowski** [comment]
As can be seen above, this is not very useful for the intersection matrix as there are no dots to highlight for an empty intersection.

Please let me know if it worked for you (you will need to update to 0.5.14).

**Comment by arcresu** [comment]
Perfect, thanks! I can confirm that it now works as expected.
