### ISSUE TITLE
Single legend for side-by-side plots?

### ISSUE THREAD

**Issue by croesel** [krassowski/complex-upset#42]
Thanks for this great package. I really like the ability to stack the intersection plots and I have been looking for something like this for a long time. I'm presenting two upsets side-by-side, but I would like like to be able to show a single legend. In the image below I would like to have just one legend showing the colors for the phyla.
Thanks! Chuck
![image](https://user-images.githubusercontent.com/6005558/84916544-35a2e780-b08c-11ea-9ad7-eb048e29822a.png)

**Comment by krassowski** [comment]
Glad to hear that the package is useful and used in the bioinformatics field! As for merging legends, it is easily possible using patchwork. I will add an example to documentation, but you basically need to:

<details>

<summary>(load the data, packages, ggplot2)</summary>

```R
library(ggplot2)
library(ComplexUpset)

movies = ggplot2movies::movies
movies[movies$mpaa == '', 'mpaa'] = NA
movies = movies[complete.cases(movies), ]
genres = c(
    'Action', 'Animation', 'Comedy', 'Drama',
    'Documentary', 'Romance', 'Short'
)
```

</details>

```R
library(patchwork)

annotations = list(
    'MPAA Raiting'=list(
        aes=aes(x=intersection, fill=mpaa),
        geom=list(
            geom_bar(stat='count', position='fill')
        )
    )
)
set.seed(0)    # for replicable example only

data_1 = movies[sample(nrow(movies), 200), ]
data_2 = movies[sample(nrow(movies), 200), ]

u1 = upset(data_1, genres, min_size=5, base_annotations=annotations)
u2 = upset(data_2, genres, min_size=5, base_annotations=annotations)

(u1 | u2) + plot_layout(guides='collect')
```

Now, this will result in the two guides (legends) being displayed on by another:

![image](https://user-images.githubusercontent.com/5832902/84932714-a10ca980-b0cc-11ea-989e-00136dc14b77.png)

Hope it helps! Please feel welcome to share more feedback.

**Comment by croesel** [comment]
This is great, thank you!
