### ISSUE TITLE
Highlight covers on-bar counts

### ISSUE THREAD

**Issue by arcresu** [krassowski/complex-upset#43]
I might be doing something wrong, but it seems that if a bar on the intersection sizes plot is highlighted, then any on-bar counts are hidden.

In the example below, the count is on the bar for the first 2 bars, but when the second is highlighted the count isn't visible on that one. I tried changing the text colours, but it didn't have any effect on the highlighted bar.

``` r
library(ggplot2)
library(ComplexUpset)
model <-
  data.frame(
    guess = c(T,T,T,T,F,F,F,F),
    real  = c(F,T,T,T,T,F,T,T)
  )

upset(
  model,
  intersect = c("guess", "real"),
  queries = list(
    upset_query(
      intersect = c("guess", "real"),
      fill = "blue"
    ),
    upset_query(
      intersect = NA,
      fill = "blue"
    )
  )
)
```

![](https://i.imgur.com/ngCZh8j.png)

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krassowski** [comment]
Thank you for reporting this and for a perfect reproducible example. This problem steams from the text ending up below the the bar. I fill fix the ordering of the layers and release it tonight (UK time).

**Comment by krassowski** [comment]
This should now work in version 0.5.15:

![image](https://user-images.githubusercontent.com/5832902/85078859-51f27180-b1bd-11ea-8954-f8e9df0b0798.png)

**Comment by arcresu** [comment]
Thanks heaps! I've tried it out and it looks great now.
