### ISSUE TITLE
upset doesn't show all overlapping elements in sets

### ISSUE THREAD

**Issue by jarekbryk** [krassowski/complex-upset#45]
Hi,

I've been trying to get upset to display all overlapping elements between sets but I can't, and its behaviour is puzzling:

```
# Example data
test <- data.frame(
  stringsAsFactors = FALSE,
           id_set1 = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
           id_set2 = c(NA, NA, NA, NA, "e", NA, NA, "h", "i", "j"),
           id_set3 = c("a", "b", NA, "d", "e", "f", "g", "h", "i", "j"),
           id_set4 = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")
        )

# Turn the values into Boolean
elements <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")

test2 = data.frame(
	set1 = ifelse(test[,1] %in% elements, 1, 0),
	set2 = ifelse(test[,2] %in% elements, 1, 0),
	set3 = ifelse(test[,3] %in% elements, 1, 0),
	set4 = ifelse(test[,4] %in% elements, 1, 0))

upset(test2, colnames(test2))
```

<img width="1179" alt="upset(test2, colnames(test2))" src="https://user-images.githubusercontent.com/7264784/85806250-69de6e00-b746-11ea-86a2-7322d8edc638.png">

I thought that the height of the bars should show counts of common elements in the given sets (their intersections, in the sense of `intersect()`), but it doesn't. For example, the plot suggests there are five common elements in sets 1, 3 and 4. But we can see from the table that there are nine (the only missing element is c in set3). On the other hand, it correctly shows that there are four common elements across all four sets (e, h, i, j). Then again, sets 1 and 4 are identical, so they have ten common elements. Where does the 1 come from on the plot? (I also don't mention here that not all combination of sets are shown)

Could someone please clarify this behaviour?

kJ

**Comment by krassowski** [comment]
Hi Jarek,

Thank you for asking this question - your feedback is greatly appreciated and I will probably link this issue from the readme or frequently asked question section (it was asked elsewhere previously) once I get time to create it.

The short answer is: this is not how the upset plots work; let's say that columns of the input data frame define binary set membership while rows define observations - then the intersection size plotted shows the number of observations which belong to exactly the highlighted sets and no other set. Think of it as always selecting the smallest regions of a Venn diagram (never two regions at a time).

To illustrate this. your input is:

![Screenshot from 2020-06-26 01-34-25](https://user-images.githubusercontent.com/5832902/85808603-40751080-b74d-11ea-8b04-296a05610bd9.png)

What you see on the plot bars is essentially the `count(intersection)` as in the frame below:
![Screenshot from 2020-06-26 01-35-04](https://user-images.githubusercontent.com/5832902/85808648-64385680-b74d-11ea-95e2-a9e75ee17110.png)

which is obviously different from what you may have expected.

There is a previous publication of [(Lex et al, 2014)](https://ieeexplore.ieee.org/document/6876017) which you may want to read to get more familiar with the concept of UpSet plots (and I recommend to cite it along with any specific implementation you decide to use if upset plots are new in your field to refer readers to more detailed description).

Just to note this, I validated your example with the reference (but currently not maintained) implementation of UpsetR, which gives exactly the same result:

![image](https://user-images.githubusercontent.com/5832902/85808556-1facbb00-b74d-11ea-8484-31daacff48d4.png)

I find it useful to think about it like this: the rows do NOT define sets: they are not elements, they are observations; the plot does not describe sets, the plot describes observations which belong to specific sets.

Please let me know if this helps or not (or if you think that there are better words to explain it)!

**Comment by krassowski** [comment]
Also, have a look at the figure in https://github.com/hms-dbmi/UpSetR/issues/72#issuecomment-597804658. The comment says that you could try using ComplexHeatmap package instead if the "intersection" mode (rather than "distinct") is what you want (but I would be afraid that it might confuse the reader if not stated explicitly that you upset plot is departing from the usual convention of counting distinct observations only). Or if you prefer to use this package, I could look into implementing the other modes, but it was not a priority/requested feature up to this point.

**Comment by jarekbryk** [comment]
Hi, 
thanks a lot for the explanation. I suspected this is a feature, not a bug ;-) as I also had checked the behaviour of UpSetR::upset and it is was the same. The figure you refer to is brilliant - if you're getting lot's of FAQ like this, it may be worthwhile to steal it into the documentation. And if you're really getting many FAQs about this, I think it's time to implement the "union" behaviour :-). I do it the hard way now, by calculating rowSums for all combinations of sets in the matrix and counting how many sums are equal to the number of sets.

`sum(rowSums(test2[,c("set1", "set3", "set4")]) == 3)`

Thanks a lot again and a great package!

**Comment by MTR164** [comment]
Hi; 
Is there any way that the "intersaction" mode is included in the upset package? I'm trying to use the complexHeatmap package instead but it's not clear how to select specific combinations. I cannot use the arguement "intersections=" in the complexheatmap package.

**Comment by krassowski** [comment]
I have some progress here, for example using:

| members\mode     | distinct | intersect | union |
|------------------|----------|-----------|-------|
| (A, B)           | 10       | 11        | 223   |
| (A, C) == (B, C) | 6        | 7         | 1123  |
| (A) == (B)       | 100      | 117       | 117   |
| (C)              | 1000     | 1013      | 1013  |
| (A, B, C)        | 1        | 1      | 1223  |

![Screenshot from 2020-12-18 19-22-26](https://user-images.githubusercontent.com/5832902/102653281-af647c80-4166-11eb-8290-6b99ded89ce9.png)

The feature of choosing the mode will be available in the next release (hopefully I will polish it over the weekend).

**Comment by krassowski** [comment]
FYI, I am also consulting extremely helpful people over at [Mathematics.SE](https://math.stackexchange.com/questions/3954172/is-there-generally-understood-set-theory-term-for-a-cap-b-setminus-c) to figure out a better terminology - please chime in if you know of a better term/have any ideas.
