### ISSUE TITLE
min_degree not working as intended

### ISSUE THREAD

**Issue by BroadbentJim** [krassowski/complex-upset#48]
The parameter min_degree fails to work as intended. When given the parameter min_degree = 0, it will plot all intersections as expected included the case of the null set of intersections. However when given the parameter min_degree = 1, it will exclude not only the null set but any set consisting of just one intersection which removes the opportunity to exclude the null set.
`0,0,0
0,0,0
0,0,1
0,1,0
0,1,1`
When tested on the above csv, we get the following outcomes:
![image](https://user-images.githubusercontent.com/5060061/88662078-5caff880-d0d1-11ea-9008-5ca8945304d3.png)
![image](https://user-images.githubusercontent.com/5060061/88662127-6afe1480-d0d1-11ea-816a-6baad2a64552.png)
In my case, I am working with categorical data dealing with cases of a medical event which is massively sparse so the vast majority of people don't have any events recording but I need to exclude them in this analysis.
Hope that this can be resolved as otherwise I am very impressed with the package.

**Comment by krassowski** [comment]
Apologies for that! I just run into this myself yesterday. I am going to fix this off-by-one error soon!

**Comment by krassowski** [comment]
Fixed in d3bd453d22199d46a0b70c9ac5491bdfa6410caa. Thank you again for opening this issue!
