### ISSUE TITLE
How to change front size of the Y-axis  label of the intersection size (barplot)?

### ISSUE THREAD

**Issue by bbalog87** [krassowski/complex-upset#51]

**Comment by krassowski** [comment]
Hi @bbalog87, thank you for asking. You can use [`upset_modify_themes()`](https://krassowski.github.io/complex-upset/reference/upset_modify_themes.html) to modify specific parts of the plot, like this:

<img src="https://user-images.githubusercontent.com/5832902/90042386-86b50d80-dcc2-11ea-9d92-bbe453e84431.png" width=300>


<details>

<summary>Optional: click to show the preparatory steps</summary>

```R
library(ComplexUpset)
movies = ggplot2movies::movies
movies[movies$mpaa == '', 'mpaa'] = NA
movies = movies[complete.cases(movies), ]
genres = c('Action', 'Animation', 'Comedy', 'Drama', 'Documentary', 'Romance', 'Short')
```

</details>

```R
upset(
    movies, genres, name='genre', min_size=100,
    themes=upset_modify_themes(
        list(
            'Intersection size'=theme(
                axis.text=element_text(size=30, face='bold'),
                axis.title=element_text(size=24, face='italic')
            )
        )
    )
)
```

Please let me know if you have any other questions, or feedback on the package. I hope it is useful!

**Comment by bbalog87** [comment]
Hi @krassowski,
Thank you for the great package. Your answer was helpful.
[testComplex.pdf](https://github.com/krassowski/complex-upset/files/5073309/testComplex.pdf)

Would you please give me another hint how to override the default colors palette with a custom color vector? I would like to change the default filled color in the bar plot with a custom list of colors  e.g. ```  COLOR=c('#ff6961','#6a3d9a', '#fb9a99', '#b2182b','#fdbf6f','#ff7f00',
          '#cab2d6','#4393c3', '#d6604d', "darkgreen") ```, each color correspond to a specific sets (Tissue).

Best,
Julien

**Comment by krassowski** [comment]
Great to hear that. For changing colour scales theare a two options, the preferred one:

```R
upset(
    movies, genres,
    min_size=100,
    base_annotations=list(
        'Intersection size'=upset_annotate(
            '..count..',
            list(
                geom_bar(aes(fill=mpaa)),
                scale_fill_manual(values=c(
                    'R'='#E41A1C', 'PG'='#377EB8',
                    'PG-13'='#4DAF4A', 'NC-17'='#FF7F00'
                ))
            )
        )
    )
)
```

and the easier but less flexible one:

```R
upset(
    movies,
    genres,
    base_annotations=list(
        'Intersection size'=intersection_size(
            counts=FALSE,
            aes=aes(fill=mpaa)
        )
    ),
    min_size=100
) & scale_fill_manual(values=c(
    'R'='#E41A1C', 'PG'='#377EB8',
    'PG-13'='#4DAF4A', 'NC-17'='#FF7F00'
))
```

Result is the same for both:

<img src="https://user-images.githubusercontent.com/5832902/90236503-c0009100-de1a-11ea-9371-7f300545cf8f.png" width=400>


Note to self: needs example in documentation, closely related to https://github.com/krassowski/complex-upset/issues/27#issuecomment-618288149

**Comment by bbalog87** [comment]
Thanks a lot!. It's worked perfectly.  
I think this is an important feature to be added  maybe in the documentation as example, since other users might be interested in such kind of customization.

Best,
Julien

**Comment by krassowski** [comment]
Great to hear it worked well! I am closing this issue now, as the example with color is now added to the documentation (and I think the changing fonts thing should be clearer now given there are more examples for themes). Thank you for bringing it up here!
