### ISSUE TITLE
combining plots into panels

### ISSUE THREAD

**Issue by taylorreiter** [krassowski/complex-upset#52]
Hello! I would like to combine multiple complex upset plots with other ggplots into a single plot panel. I usually use `ggpubr::ggarrange` for this, or `cowplot::plot_grid`. When I use these functions on a complex upset, only the intersections are plotted. I'm including and example output plot as it is currently working. I like using `ggarrange` and `plot_grid` to add labels, control the relative size of plots in a panel, and combine many types of plots. Is it possible to make complex upset compatible with either of these packages? Is there a different workaround for combining many different plots? 
![combine_complex_upset](https://user-images.githubusercontent.com/23057646/92307074-adc0d100-ef48-11ea-8165-6aa737d56311.png)

**Comment by krassowski** [comment]
I have tried several approaches ways but could not make it work with `cowplot::plot_grid` - sorry :(

However, you could easily combine the plots together if you are ok with using [patchwork](https://github.com/thomasp85/patchwork) instead, see #42 for an example.

**Comment by taylorreiter** [comment]
The patchwork solution is perfect, thank you! I scanned through the issues before posting this but didn't see it :)

**Comment by krassowski** [comment]
Thanks for getting back to me, I am glad that it helped! I will add this example to the documentation.
