### ISSUE TITLE
exporting plot with a transparent background

### ISSUE THREAD

**Issue by taylorreiter** [krassowski/complex-upset#54]
Hello! I'm using a complex upset plot in a presentation. I exported the plot from R and it has a white background. Is it possible for complex upset plots to have a transparent background? I use a colored slide background, so transparent background of plots is more aesthetically pleasing. ggplot has background automatically set to transparent, but I couldn't figure out how to control that parameter in complex upset. 

Thank you for such a wonderful visualization! It really helps me tell the story of my research!

**Comment by krassowski** [comment]
You can change the background fill with `theme` → `plot.background`:

```R
(
    upset(movies, genres, name='genre', width_ratio=0.1)
    & theme(plot.background = element_rect(fill = 'transparent', color = NA))
)
ggsave('test.png', bg = "transparent")
```

Which gives:

![Screenshot from 2020-09-11 03-42-29](https://user-images.githubusercontent.com/5832902/92847222-d6c9e180-f3e0-11ea-8f4a-cad7cf3108e4.png)

I am working on the stripes at the moment...

**Comment by krassowski** [comment]
With the new 0.5.16 version, you should be able to set semi-transparent stripes colours too:

```R
(
    upset(
        movies, genres, name='genre', width_ratio=0.1,
        stripes=c(alpha('red', 0.3), alpha('white', 0.3))
    )
    & theme(plot.background = element_rect(fill='transparent', color=NA))
)
ggsave('test2.png', bg = "transparent")
```

![Screenshot from 2020-09-11 05-07-57](https://user-images.githubusercontent.com/5832902/92857562-c586d200-f3ec-11ea-85e0-67a5252b6874.png)

I added this to the [examples](https://krassowski.github.io/complex-upset/articles/Examples_R.html#making-the-plot-transparent).

Please let me know if it works for you.

**Comment by taylorreiter** [comment]
This is wonderful, thank you!!
