### ISSUE TITLE
Add totals to stacked interssection barplot

### ISSUE THREAD

**Issue by NatashaJorge** [krassowski/complex-upset#58]
Hello!
Thanks for the great package, upSet plots are a great and with your add-ons, we can show even more stuff.

I'm currently using the R code provided for the stacked barplot in the intersection size part of it. If I set counts=T, I get the counts for each of the respective sections inside the bar. Obviously, sometimes the values overlap. So I was wondering if it is possible to change the stacked barplot for the percentage form (where all bars have the same high and the parts correspond to the percentage of the group) and/or show only the total size of the intersection group instead of the size of the parts?

Thanks for your time and attention,
Best regards,
Natasha

**Comment by krassowski** [comment]
Hi Natasha,

Yes, it is possible to display percentages and add a different kind of label - have a look here: https://github.com/krassowski/complex-upset/issues/36#issuecomment-643460954 and let me know if you need help adapting these examples for your use-case. I will work on making it easier for the user soon (in a matter of a weekend or two I think).

Hope it helps!
Best wishes,
Mike

**Comment by krassowski** [comment]
I hope that you were able to find what you was looking for. I believe that relevant examples are now in the documentation, so I will close this issue. Please feel free to reopen if I did not address your problem well enough.
