### ISSUE TITLE
Upset with Data.table object having Error in stack.data.frame(data, intersect).

### ISSUE THREAD

**Issue by akhst7** [krassowski/complex-upset#63]
Hi, 

I have this data.table;

```
str(category.mini)
Classes ‘data.table’ and 'data.frame':	174 obs. of  8 variables:
 $ Plurality                     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Sex                           : int  0 0 0 0 1 0 1 1 1 0 ...
 $ Delivery                      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Farm_Status                   : int  0 0 1 0 0 0 1 1 0 0 ...
 $ Mom_allergic_disease          : int  1 0 0 0 1 1 1 0 0 0 ...
 $ Mom_allergic_symptom_pregnancy: int  1 0 0 0 1 0 0 0 0 0 ...
 $ AD_1yr                        : int  0 0 1 0 0 0 0 0 0 0 ...
 $ Wheeze_1yr                    : int  1 1 0 0 1 0 0 0 0 0 ...
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, "index")= int(0) 
```
I created a chr vector for the intersecting columns as follows;

`upset.colname<-names(category.mini) `

```
str(upset.colname)
 chr [1:8] "Plurality" "Sex" "Delivery" "Farm_Status" "Mom_allergic_disease" "Mom_allergic_symptom_pregnancy" "AD_1yr" "Wheeze_1yr"
```
After that,  I run a following ;

`upset(category.lipid.mini, lipid.upset.colname, min_size=100, width_ratio=0.1)`
 
and I got this error, `Error in stack.data.frame(data, intersect) : no vector columns were selected`

Initially, I though the data.table object was not compatible with upset but a data.table version of a demo, the movie run just fine with upset.  I converted category.mini to tibble but I still have the same issue.   I'd really appreciate any input on this. 

Thanks.

**Comment by krassowski** [comment]
Hi @akhst7, thank you for opening this issue! I would be happy to help you solving this issue, it would make it much easier if you could provoide a minimal copy-paste example which demonstrates the error.

**Comment by akhst7** [comment]
@krassowski ,  
 
Thanks for a quick response.   Here is the partial data in question.   

```
Plurality Sex Delivery Farm_Status Mom_allergic_disease Mom_allergic_symptom_pregnancy AD_1yr Wheeze_1yr
 1:         0   0        0           0                    1                              1      0          1
 2:         0   0        0           0                    0                              0      0          1
 3:         0   0        0           1                    0                              0      1          0
 4:         0   0        0           0                    0                              0      0          0
 5:         0   1        0           0                    1                              1      0          1
 6:         0   0        0           0                    1                              0      0          0
 7:         0   1        0           1                    1                              0      0          0
 8:         0   1        0           1                    0                              0      0          0
 9:         0   1        0           0                    0                              0      0          0
10:         0   0        0           0                    0                              0      0          0

```
If this works, them it must be some format issues that upset doesn't like in my R. 

thanks.

**Comment by krassowski** [comment]
It works for me with the example data when I decrease the `min_size` (you could not have an intersection with 100 members in the dataset of 10 rows); it might also apply to your full dataset. Please let me know if this suggestion helps!

Action items:
 - [ ] the error message should be more specific

I run the following code:

```R
library(ComplexUpset)
category.mini = read.table('issue_63.txt')
upset.colname = names(category.mini)
upset(data.table(category.mini), upset.colname, min_size=1, width_ratio=0.1)
```

and got:

<img src="https://user-images.githubusercontent.com/5832902/97054153-2c66e180-157c-11eb-8ae7-f74151fb0381.png" width=500>

The `issue_63.txt` file contains the copy-pasted data from your commment above.

**Comment by akhst7** [comment]
@krassowski, 
Then it has  probably some to do with the way data.table writes column or perhaps attributes.  If I send you the entire file in question as .rds, can you try and see if you get the same error I am having ?

**Comment by krassowski** [comment]
I do not see the `.rds` file. Could you prepare a [minimal reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), please?

**Comment by akhst7** [comment]
@krassowski 

Sorry took a while but here is the 

Also, my R setup and os are as follows;

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin18.7.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.10_2/lib/libopenblasp-r0.3.10.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ComplexUpset_0.5.18 ggplot2_3.3.2.9000  data.table_1.13.2  

loaded via a namespace (and not attached):
 [1] circlize_0.4.11      shape_1.4.5          GetoptLong_1.0.4     tidyselect_1.1.0     purrr_0.3.4          haven_2.3.1         
 [7] carData_3.0-4        colorspace_1.4-1     vctrs_0.3.4          generics_0.0.2       stats4_4.0.3         rlang_0.4.8         
[13] pillar_1.4.6         withr_2.3.0          foreign_0.8-80       glue_1.4.2           RColorBrewer_1.1-2   BiocGenerics_0.35.4 
[19] readxl_1.3.1         uuid_0.1-4           matrixStats_0.57.0   lifecycle_0.2.0      munsell_0.5.0        gtable_0.3.0        
[25] cellranger_1.1.0     zip_2.1.1            GlobalOptions_0.1.2  rio_0.5.16           forcats_0.5.0        ComplexHeatmap_2.5.6
[31] IRanges_2.23.10      curl_4.3             parallel_4.0.3       broom_0.7.2          Rcpp_1.0.5           scales_1.1.1        
[37] backports_1.1.10     S4Vectors_0.27.14    abind_1.4-5          rjson_0.2.20         hms_0.5.3            png_0.1-7           
[43] digest_0.6.26        stringi_1.5.3        openxlsx_4.2.2       rstatix_0.6.0        dplyr_1.0.2          clue_0.3-57         
[49] grid_4.0.3           tools_4.0.3          magrittr_1.5         patchwork_1.0.1      tibble_3.0.4         cluster_2.1.0       
[55] crayon_1.3.4         car_3.0-10           tidyr_1.1.2          pkgconfig_2.0.3      ellipsis_0.3.1       xml2_1.3.2          
[61] officer_0.3.14       rstudioapi_0.11      R6_2.4.1             compiler_4.0.3      

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G6032


[category.rds.zip](https://github.com/krassowski/complex-upset/files/5433860/category.rds.zip)

**Comment by akhst7** [comment]
I figured this out.  A culprit was **min_size=100**.   If I fire `upset(category.lipid.mini, lipid.upset.colname,  width_ratio=0.1)`, I get the upset plot.  I still don't know how **min_size=100**. affects the selection of columns in the question though.

Anyway, thanks for all the help.  ComplexUpset is a awesome package.  To me it is much easier to implement than the UpsetR package.
