### ISSUE TITLE
Delete axis.text.x of intersection matrix 

### ISSUE THREAD

**Issue by akhst7** [krassowski/complex-upset#64]
I have a following code to generate the upset plot blow.

```R
upset(
ab.upset,
lipid.upset.colname,
annotations = list(
"Cer.C14.0" = list(
aes=aes(x=intersection, y=Cer.C14.0),
geom=list(
geom_jitter(),
geom_boxplot(outlier.shape = NA)
)
)
),
base_annotations=list(
'Intersection count'= intersection_size(counts=T),
'Intersection ratio'=intersection_ratio(text_aes=aes_(label=upset_text_percentage()))
),
width_ratio = 0.1,
wrap = T,
keep_empty_groups = F,
themes=list(defalut=theme(axis.text.x = element_blank())
)
)
```

![Untitled 001](https://user-images.githubusercontent.com/3075799/97355203-f3c15380-186c-11eb-95c2-04e8f273c22b.png)

I'd like to use the default theme since it generates color coded intersections (True vs False)  but an issue I am having is the pile up on x axis text.   I'd appreciate pointers on how to remote the pile up.  

Thanks in advance.

**Comment by krassowski** [comment]
You have a typo. It's `default`, not `defalut`.

**Comment by krassowski** [comment]
You would probably want:

```R
        themes=list(
            default=theme(
                axis.ticks.x=element_blank(),
                axis.text.x=element_blank(),
            ),
            intersections_matrix=theme(
                axis.ticks.x=element_blank(),
                axis.text.x=element_blank(),
            )
        )
```

Or, if you only care about the color codes:

```R
    themes=upset_modify_themes(list(
        intersections_matrix=scale_color_discrete()
    ))
```

**Comment by krassowski** [comment]
By the way you can also do:

```R
        themes=upset_modify_themes(list(
            intersections_matrix=scale_color_manual(
                values=list('TRUE'='black', 'FALSE'='grey85'),
            )
        ))
```

**Comment by akhst7** [comment]
@krassowski ,

Thanks.    I tried your last suggestion and I run the following;

`upset(
  ab.upset,
  lipid.upset.colname,
  annotations = list(
    "Cer.C14.0" = list(
      aes=aes(x=intersection, y=Cer.C14.0),
      geom=list(
        geom_jitter(),
        geom_boxplot(outlier.shape = NA)
        )
      )
    ),
  base_annotations=list(
    'Intersection count'= intersection_size(counts=T),
    'Intersection ratio'=intersection_ratio(text_aes=aes_(label=upset_text_percentage()))
  ),
  width_ratio = 0.1,
  wrap = T,
  keep_empty_groups = F,
  tthemes=upset_modify_themes(list(
    intersections_matrix=scale_color_manual(
      values=list('TRUE'='green', 'FALSE'='blue')
    )
  ))
)`

then, I got this error;

`rror in upset_data(data, intersect, ...) : 
  unused argument (tthemes = list(list(list(list("black", 0.5, 1, "butt", FALSE, TRUE), list("white", "black", 0.5, 1, TRUE), list("", "plain", "black", 11, 0.5, 0.5, 0, 0.9, c(0, 0, 0, 0), FALSE, TRUE), NULL, NULL, NULL, list(NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, c(2.75, 0, 0, 0), NULL, TRUE), list(NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, c(0, 0, 2.75, 0), NULL, TRUE), NULL, list(NULL, NULL, NULL, NULL, NULL, 1, 90, NULL, c(0, 2.75, 0, 0), NULL, TRUE), NULL, list(NULL, NULL, NULL, NULL, NULL, 0, 
    -90, NULL, c(0, 0, 0, 2.75), NULL, TRUE), list(NULL, NULL, "grey30", 0.8, NULL, NULL, NULL, NULL, NULL, NULL, TRUE), list(NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, c(2.2, 0, 0, 0), NULL, TRUE), list(NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, c(0, 0, 2.2, 0), NULL, TRUE), NULL, list(NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, c(0, 2.2, 0, 0), NULL, TRUE), NULL, list(NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, c(0, 0, 0, 2.2), NULL, TRUE), list(), NULL, NULL, NULL,`

Any thoughts ? 

Thanks.

**Comment by krassowski** [comment]
You have a typo. It is `tthemes`, not `themes`. Please use triple backtick when providing multi-line code, it makes it more readable.

**Comment by akhst7** [comment]
Sorry.   It works now.

**Comment by krassowski** [comment]
Glad it works for you :)
