### ISSUE TITLE
Intersection membership values

### ISSUE THREAD

**Issue by akhst7** [krassowski/complex-upset#65]
@krassowski, 

Is there any way to extract  values  for intersection groups , for example 1 for Animation + Comedy+Drama, 2 for Animation+Drama..... ? 

thanks.

**Comment by krassowski** [comment]
Yes, use [`upset_data()`](https://krassowski.github.io/complex-upset/reference/upset_data.html), this is what is used under the hood to build the plots.

**Comment by krassowski** [comment]
Did it help?

**Comment by akhst7** [comment]
Is there any way to assign **$plot_intersections_subset values** to each individual samples by perhaps generating **$plot_intersections_subset_membership** ?  For instance, 174 samples with ten $plot_intersections_subsets generate  $plot_intersections_subset_membership, as follows

[```
1]  1  2  1  3  3  3  1  1  1  1  3  1  1  1  1  3  1  1  2  3  3  1  1  3  1  3  1  1  1  1  3  1  1  1  1  1  4  4  1  5  6
 [42]  7  6  8  5  6  6  5  6  5  4  6  4  6  9  4  5  2  5  4  4  6  4  4  4  4  5  6  6  6  5  5  6  6  4  6  6  4  5  5  6  4
 [83]  6  4  5  6  6  9  9  9  9  5  9  9  9  9  9  9  9  2  2  2  2  2  5  2  2  2  2  2 10 10  8  7 10  7 10  8  7  8  8  8 10
[124]  6  8  6  7  2  7  7  7  3  5  8  7  2  7  2  2  2  7  8  8  7 10  5  5  8 10  5  3  3  5 10  7 10  5  2  7  2  2  2  7  7
[165]  7  8  8  8  8  8  8  8 10 10
```

Thanks.

**Comment by krassowski** [comment]
Please provide a minimal reproducible motivating example - I do not understand what you wish to achive.

**Comment by akhst7** [comment]
@krassowski ,

I got a little confused.   `upset_data` give me the enough detailed output I need, particularly, `$intersected` and `$with_sizes`.  

Thanks.
