### ISSUE TITLE
Colors stacked bars

### ISSUE THREAD

**Issue by StefanieMeier** [krassowski/complex-upset#67]
Hi!
I used complex-upset to create an upset plot with stacked bar plot (really easy thanks to the great documentation!), but couldn't figure out how to change the colors of the stacked bars. 
Thanks for your help!

**Comment by krassowski** [comment]
See: https://github.com/krassowski/complex-upset/issues/27#issuecomment-618288149. Note for self: this need an example after #21.

**Comment by krassowski** [comment]
This is now (in version 0.6.0) quite easy when using `intersection_size` or  `upset_annotate` by adding the ggplot2 scale you want to use. Here is an example from [updated documentation](https://krassowski.github.io/complex-upset/articles/Examples_R.html#3-2-fill-the-bars):

```R
upset(
    movies,
    genres,
    base_annotations=list(
        'Intersection size'=intersection_size(
            counts=FALSE,
            aes=aes(fill=mpaa)
        ) + scale_fill_manual(values=c(
            'R'='#E41A1C', 'PG'='#377EB8',
            'PG-13'='#4DAF4A', 'NC-17'='#FF7F00'
        ))
    ),
    width_ratio=0.1
)
```

![image](https://user-images.githubusercontent.com/5832902/101093424-a4c8b580-35b2-11eb-99e1-dd1e9dfe187b.png)

Thank you for the suggestion!

**Comment by StefanieMeier** [comment]
Awesome! Thanks for the quick response and the updated documentation
