### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by adomingues** [krassowski/complex-upset#68]
Hi @krassowski , 

I just wanted to ask if you have any plans of submitting this package to cran? I know it's a lot of work :)

Cheers.

**Comment by krassowski** [comment]
Thank you. Yes, I will look into this in December (there are some API improvements needed that would be better done before cutting 1.0, but it is getting there).

**Comment by krassowski** [comment]
I submitted version 0.7.2 to CRAN today. My first submission ever, so not sure how it will go. I will let you know once it is accepted (or rejected).

**Comment by krassowski** [comment]
Done: https://cran.r-project.org/web/packages/ComplexUpset/index.html

Due to a crazy development pace last weekend it is tad outdated already (0.7.3). I will aim to submit the newest 0.8.x within two weeks from today (once the dust of the novelty settle and potential associated bugs get fixed).

**Comment by adomingues** [comment]
Thanks a lot @krassowski! This will help a lot to create conda packages and also comply rules that some insitutions might have in pace (only CRAN packages allowed).

**Comment by krassowski** [comment]
Yes, a conda package would be helpfu! Just in case of you wish to contribute it, please feel welcome to do so, and to include me in the process (giving a formal nod here just in case if this would be required).

**Comment by adomingues** [comment]
I will have a go at it during Christmas :)

**Comment by krassowski** [comment]
I will leave this screenshot here, just in case if anyone is gonna ask why the 0.9 version is not on CRAN yet:

![Screenshot from 2020-12-21 00-30-11](https://user-images.githubusercontent.com/5832902/102728475-14190600-4324-11eb-85d1-b3c56b3e56bc.png)

**Comment by krassowski** [comment]
Hi @adomingues, I have now created a PR for conda-forge: https://github.com/conda-forge/staged-recipes/pull/14522. I have not contributed a conda package before - please feel welcome to chime in with your expertise.

**Comment by krassowski** [comment]
Ok, we are on conda-forge now :tada:

**Comment by adomingues** [comment]
Super cool! Sorry for not being of much help but work has been crazy at the moment - luckily my input was not necessary anyway :)
