### ISSUE TITLE
Add n_intersections argument

### ISSUE THREAD

**Issue by thegargiulian** [krassowski/complex-upset#70]
Hi @krassowski,

Thank you for all of your work on this!

Would you consider adding an `n_intersections` argument like the one available in [ggupset](https://github.com/const-ae/ggupset)? I've been using the `min_size` argument, but I'd like to be able to specify a constant number of intersections (the `n_intersections` largest) to display across plots of different subsets of my data that may vary drastically in the number of displayed intersections for a fixed `min_size` value.

**Comment by krassowski** [comment]
Just a guess: are you perhaps looking for `min_degree` and `max_degree` arguments? I think it might be it; although I do not have an example prepared, it is documented in reference, here: https://krassowski.github.io/complex-upset/reference/upset_data.html

Please let me know if it works for you.

**Comment by thegargiulian** [comment]
That's a great feature, but not quite what I'm looking for in my use case. 

The real issue here is that I have too much data to visualize all at once (15 individual set elements) and the frequency magnitudes of specific sets vary greatly between subsets of the data.  I'd like to be able to specify something like `n_intersections = X` to have a consistent presentation of the top X sets in each category regardless of their individual frequencies or degrees

**Comment by krassowski** [comment]
Thank you for clarification. I added `n_intersections` argument to version 0.6.0, which you can get by re-installing the package.

Here is an example I now added to [the documentation](https://krassowski.github.io/complex-upset/articles/Examples_R.html#0-1-selecting-intersections):

```R
upset(movies, genres, width_ratio=0.1, n_intersections=15)
```
![image](https://user-images.githubusercontent.com/5832902/101093203-561b1b80-35b2-11eb-9a35-f27fc3c78eeb.png)

Thank you for the suggestion and please let me know if it works well for you.

**Comment by thegargiulian** [comment]
This does exactly what I need! Thank you!
