### ISSUE TITLE
Setting limit for y-axis 

### ISSUE THREAD

**Issue by annaduenser** [krassowski/complex-upset#71]
Dear @krassowski,

I successfully created upset plots, thanks to you and the great documentation. I was just wondering if it is possible to set a fixed y-axis limit like with ylim() for the Intersection Size? I did not find anything on this. 

Thank you so much.

Best regards,
Anna

**Comment by annaduenser** [comment]
Hi agian,
I found a solution (see attached code) and am closing this issue. But I am not quite sure if this is the best solution.

```
isize = intersection_size(counts=T)
isize$geom = c(
    isize$geom,
    ylim(0,400)
)
```

Thanks anyway,
Anna

**Comment by krassowski** [comment]
Dear Anna,

Thank you for opening this issue. This was indeed not documented and as you discovered required a two step process. I have just prepared a new version (0.6.0) which allows to simply `intersection_size() + ylim(0, 400)`, as in the example [3.8 Further adjustments using ggplot2 functions](https://krassowski.github.io/complex-upset/articles/Examples_R.html#3-8-further-adjustments-using-ggplot2-functions):

```R
upset(
    movies, genres, width_ratio=0.1,
    base_annotations = list(
        'Intersection size'=(
            intersection_size()
            + ylim(c(0, 700))
            + theme(plot.background=element_rect(fill='#E5D3B3'))
            + ylab('# observations in intersection')
        )
    ),
    min_size=10
)
```

![image](https://user-images.githubusercontent.com/5832902/101092548-bbbad800-35b1-11eb-99e6-8e6dc043345e.png)

Please feel welcome to ask any further questions or provide suggestions. Thank you again!

Best wishes,
Mike

**Comment by annaduenser** [comment]
Dear Mike,

Thank you for your answer and for the info! This looks really cool. Looking forward to version 0.6.0.

Best wishes,
Anna
