### ISSUE TITLE
Intersection size as percentage

### ISSUE THREAD

**Issue by angelosarmen** [krassowski/complex-upset#76]
Hi,

How can I display the intersection size as percentage (of all items) instead of count in the Y axis?

**Comment by krassowski** [comment]
Hi @angelosarmen,

thank you for opening this issue! Would something like this:

<img src="https://user-images.githubusercontent.com/5832902/102013047-88144680-3d45-11eb-8206-f1011620693e.png" width=400px>

```R
upset(
    movies, genres,
    min_size=10,
    base_annotations=list(
        'Intersection size'=(
            intersection_size(
                text_aes=aes(
                    y=ifelse(
                        ..count.. <= 0.85 * max(..count..),
                        ..count../sum(..count..),
                        (..count.. * 0.85) / sum(..count..)
                    )
                )
            )
            + aes(y=..count../sum(..count..))
            + ylab('Intersection size percentage')
            + scale_y_continuous(labels=scales::label_percent(accuracy=1))
        )
    )
)
```

 work for you?

**Comment by angelosarmen** [comment]
Thank you for the prompt reply! It worked after I upgraded to the last version of the package. I also managed to get percentages for the set sizes:

<pre><code>
upset(
    movies, genres,
    min_size=10,
    base_annotations=list(
        'Intersection size'=(
            intersection_size(
                text_aes=aes(
                    y=ifelse(
                        ..count.. <= 0.85 * max(..count..),
                        ..count../sum(..count..),
                        (..count.. * 0.85) / sum(..count..)
                    )
                )
            )
            + aes(y=..count../sum(..count..))
            + ylab('Intersection size percentage')
            + scale_y_continuous(labels=scales::label_percent(accuracy=1))
        )
    ),
    set_sizes=(
        upset_set_size()
        + aes(y=..count../sum(..count..))
        + ylab('Set size')
        + scale_y_continuous(labels = scales::label_percent(accuracy=1), trans = "reverse")
        + theme(axis.text.x = element_text(angle = 90))
    )
)
</code></pre>

![upset_1](https://user-images.githubusercontent.com/23380056/102083660-97b28e80-3e1c-11eb-9f3d-0a4961cedc4f.png)

The percentages however, seem to be of the items in the retained intersection. If I change the `min_size` I get different percentages:

<pre><code>
upset(
    movies, genres,
    min_size=200,
    base_annotations=list(
        'Intersection size'=(
            intersection_size(
                text_aes=aes(
                    y=ifelse(
                        ..count.. <= 0.85 * max(..count..),
                        ..count../sum(..count..),
                        (..count.. * 0.85) / sum(..count..)
                    )
                )
            )
            + aes(y=..count../sum(..count..))
            + ylab('Intersection size percentage')
            + scale_y_continuous(labels=scales::label_percent(accuracy=1))
        )
    ),
    set_sizes=(
        upset_set_size()
        + aes(y=..count../sum(..count..))
        + ylab('Set size')
        + scale_y_continuous(labels = scales::label_percent(accuracy=1), trans = "reverse")
        + theme(axis.text.x = element_text(angle = 90))
    )
)
</code></pre>

![upset_2](https://user-images.githubusercontent.com/23380056/102083795-ca5c8700-3e1c-11eb-9600-7fd6946b5f1e.png)

Is it possible to show percentages of _all_ items, i.e., before applying `min_size`? I tried setting `min_max_early = FALSE` but it doesn't make a difference.

**Comment by krassowski** [comment]
Would dividing by `nrow(movies)` work for you?

```R
upset(
    movies, genres,
    min_size=200,
    min_max_early=FALSE,
    base_annotations=list(
        'Intersection size'=(
            intersection_size(
                text_aes=aes(
                    y=ifelse(
                        ..count.. <= 0.85 * max(..count..),
                        ..count../nrow(movies),
                        (..count.. * 0.85) / nrow(movies)
                    )
                )
            )
            + aes(y=..count../nrow(movies))
            + ylab('Intersection size percentage')
            + scale_y_continuous(labels=scales::label_percent(accuracy=1))
        )
    ),
    set_sizes=(
        upset_set_size()
        + aes(y=..count../nrow(movies))
        + ylab('Set size')
        + scale_y_continuous(labels = scales::label_percent(accuracy=1), trans = "reverse")
        + theme(axis.text.x = element_text(angle = 90))
    )
)
```

<img stc="https://user-images.githubusercontent.com/5832902/102093298-e78f5680-3e18-11eb-8a63-12997cb311ef.png">

**Comment by angelosarmen** [comment]
Oh yes, of course. Thank you!
