### ISSUE TITLE
Showing percentages instead of actual frequencies in UpSet

### ISSUE THREAD

**Issue by roozmehr15** [krassowski/complex-upset#85]
Hi,

Is there a way to show percentages on UpSet charts instead of actual counts? Specifically, is there an argument for that purpose that I can add to the following command? 

upset(data = ... , intersect = c(...), ...) 

Thank you.

**Comment by krassowski** [comment]
Please read the documentation, especially [3.7 Showing percentages
](https://krassowski.github.io/complex-upset/articles/Examples_R.html#3-7-showing-percentages) and [10. Display percentages
](https://krassowski.github.io/complex-upset/articles/Examples_R.html#10-display-percentages) and [this issue](https://github.com/krassowski/complex-upset/issues/76) and let me know if it helps.

**Comment by krassowski** [comment]
I assume that it helped and will close this issue now.
