### ISSUE TITLE
how to order intersection group manually?

### ISSUE THREAD

**Issue by lijing28101** [krassowski/complex-upset#91]
Hi, I used upsetR before, and then find complex-upset is more flexible, especially for the additional component. However, I can't find a way to order the intersection group manually, which upsetR can do.  
Is there any way I can rearrange the order?

Thanks,
Jing

**Comment by krassowski** [comment]
Thanks for opening this issue. After updating to the latest 1.1 version with:

```R
if(!require(devtools)) install.packages("devtools")
devtools::install_github("krassowski/complex-upset")
```

You should be able to specify intersections manually and turn off sorting with:

```R
upset(
    movies,
    genres,
    width_ratio=0.1,
    sort_intersections=FALSE,
    intersections=list(
        'Comedy',
        'Drama',
        c('Comedy', 'Romance'),
        c('Drama', 'Romance'),
        'Outside of known sets',
        'Action'
    )
)
```

<img src="https://user-images.githubusercontent.com/5832902/104496036-5acee880-55d0-11eb-98b9-a2526aba28e2.png" width=400>
