### ISSUE TITLE
order intersection group mannually

### ISSUE THREAD

**Issue by lijing28101** [krassowski/complex-upset#92]
Hi, I used upsetR before, and then find complex-upset is more flexible, especially for the additional component. However, I can't find a way to order the intersection group manually, which upsetR can do.  
Is there any way I can rearrange the order?

Thanks,
Jing

**Comment by krassowski** [comment]
Note: duplicate of https://github.com/krassowski/complex-upset/issues/91 (just for anyone who will arrive here from a search engine in the future).
