### ISSUE TITLE
"Unused argument" issue when using the "intersections" parameter

### ISSUE THREAD

**Issue by sandragr83** [krassowski/complex-upset#94]
Hi,

I am trying to replicate the next script with the movies dataset following up the pipeline in this link https://krassowski.github.io/complex-upset/articles/Examples_R.html.  I need to understand it well as I want to apply it for my dataset to only select and plot specific intersections:

```R
upset(
    movies,
    genres,
    width_ratio=0.1,
    sort_intersections=FALSE,
    intersections=list(
        'Comedy',
        'Drama',
        c('Comedy', 'Romance'),
        c('Romance', 'Drama'),
        'Outside of known sets',
        'Action'
    )
)
```
I, however, get the next error:
**Error in upset_data(data, intersect, ...) : 
  unused argument (intersections = list("Comedy", "Drama", c("Comedy", "Romance"), c("Romance", "Drama"), "Outside of known sets", "Action"))**

![Screenshot 2021-01-15 at 13 10 12](https://user-images.githubusercontent.com/60780363/104725930-13ad3880-5733-11eb-9b71-d436da31c394.png)

I did try with the version 0.5.11 and thought it may be an issue that was fixed in the next versions, but I installed the lastest in r-cran v.1.0.3, and the issue continues.

how can I solve this?

Thank you

ComplexUpset version: 1.0.3

**Comment by krassowski** [comment]
Argument `intersections` is only available in version 1.1. You are using version 1.0.3. You need to update to version 1.1 (which is not yet available on CRAN because they have a policy of only accepting publication once every 2-3 months). You can update using:

```R
if(!require(devtools)) install.packages("devtools")
devtools::install_github("krassowski/complex-upset")
```

and restarting R afterwards. Also see https://stackoverflow.com/a/65735917/6646912

**Comment by sandragr83** [comment]
Thank you so much! this solved the issue I did even manage to apply it in my dataset  :) And yes, I am the one who posted the question in stackoverflow :) thank you for that too, I just didn't get a message that an answer was posted. this is an awesome package btw!

**Comment by krassowski** [comment]
Happy it helped! Closing this issue as 1.1 is already on CRAN.
