### ISSUE TITLE
How to replace set size bar chart with the percent stacked bar chart?

### ISSUE THREAD

**Issue by zwangunc** [krassowski/complex-upset#98]
**Objective**

**Code**

```R
>dput(head(bva))
structure(list(sample1 = c(0.1, 0.25, 0, 0.33, 0.005, 0.315), 
    sample2 = c(0.002, 0, 0.28, 0.22, 0.4, 0.098), sample3 = c(0, 
    0.4333, 0.42, 0, 0, 0.1467), sample4 = c(0.3175, 0.2333, 
    0.0142, 0.435, 0, 0), type = c("t1", "t1", "t2", "t3", "t4", 
    "t4")), row.names = c(NA, 6L), class = "data.frame")

>library(reshape2)
>bva_melt <- melt(bva, id.vars = 'type')

upset(bva,
      intersect_column,sort_intersections_by=c('degree', 'cardinality'),
      base_annotations=list(
          'Intersection size'=intersection_size(
              counts=FALSE,
              mapping=aes(fill=type)
          )
      ),set_sizes=(
          upset_set_size(geom=geom_bar(inherit.aes = FALSE,data=bva_melt,stat = 'identity',
                  aes(y=factor(variable), x = as.numeric(value), fill = type)))),width_ratio=0.1, theme=upset_default_themes(text=element_text(size=15)))
@krassowski 
```

**Screenshot or illustration**

**Context (required)**

ComplexUpset version: 1.0.3

<details>
<summary>R version details</summary>

```R
<!-- $platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.3"

$year
[1] "2020"

$month
[1] "10"

$day
[1] "10"

$`svn rev`
[1] "79318"

$language
[1] "R"

$version.string
[1] "R version 4.0.3 (2020-10-10)"

$nickname
[1] "Bunny-Wunnies Freak Out" -->
```

</details>

<details>
<summary>R session information</summary>

```R
<!-- R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 -->
```

</details>

**Comment by zwangunc** [comment]
Hi Michał, 

I want to replace the set size bar chart with the percent stacked bar chart to reflect the relative abundance. Is this possible to achieve this? It might be difficult because my relative abundance data can come from a different data frame. For instance, data frame for intersection size might be part of the complete data frame. This complete data frame will be used to plot the percent stacked bar chart. Then the information we get is the relative abundance of the intersection dataset to the whole dataset. In addition, data within the intersection dataset will be marked in a different color as well. 

Thank you!

**Comment by krassowski** [comment]
> I want to replace the set size bar chart with the percent stacked bar chart to reflect the relative abundance. Is this possible to achieve this?

Yes, there is a section of documentation for that: https://krassowski.github.io/complex-upset/articles/Examples_R.html#10-display-percentages

> It might be difficult because my relative abundance data can come from a different data frame.

This is not tidy data and not supported in general. It can be done if you just add your custom plot on top of what complex upset does. You would:
- plot the upset plot lower part by disable the set sizes bar plot (using `base_annotations=list()`)
- use the `upset_data()` function to get the information on order of intersections
- create your own percentage barplot
- stack it on top of the upset plot using [patchwork](https://patchwork.data-imaginist.com/); you may need to wrap the upset plot

> For instance, data frame for intersection size might be part of the complete data frame. This complete data frame will be used to plot the percent stacked bar chart. Then the information we get is the relative abundance of the intersection dataset to the whole dataset.

In general it should be possible to use the full data frame and let the complex upset do the math. Complex upset can filter out intersections using multiple criteria, or it  can plot very specific, user-defined intersections (though you would need to upgrade to version [1.1](https://github.com/krassowski/complex-upset/releases/tag/v1.1.0) from GitHub), so there should be no need for creating a subset data frame. Performance should not be a concern either, complex upset was heavily optimized to handle relatively large datasets (rule of thumb on maximal size would be 10^7 with up to 50 sets, 10^8 with up to 20 sets, 10^9 with <5 sets assuming about 64 GB of RAM available; this is assuming no other columns and exact numbers of sets are probably lower - this is from my memory; `group_by` and non-default modes can greatly exacerbate the performance). If either the filtering or performance are the reason for you having te subset dataframe please open an issue on this.

**Comment by zwangunc** [comment]
Hi Michał,

Thank you for the suggestion. I have no problems with plotting percentages via base_annotations(). But I was not able to achieve this with set_size(). Could you please let me know what I did wrong? Then I think I can use Patchwork package to solve my problem. Thank you!

```{r}
upset(bva,
      intersect_column,sort_intersections_by=c('degree', 'cardinality'),
      base_annotations=list(),
      set_sizes = (upset_set_size(geom=
                  geom_bar(fill=type, stat='count', position='fill'))+ scale_y_continuous(labels=scales::percent_format())))
```

Error in rep(value[[k]], length.out = n) : 
  attempt to replicate an object of type 'closure'

**Comment by krassowski** [comment]
Oh, sorry I misread your question (this is why a visual example and copy-pastable code example helps). You do not need patchwork then! You only need to change `scale_y_continuous` to `scale_x_continuous` as this is ggplot is flipped via `coord_flip()` (for compatibility with older ggplot versions that do not have the orientation argument). Please note that this will change in future versions (once I am sure that the new ggplot2 version is adopted by majority of users). Example:

```
upset(
    movies,
    genres,
    width_ratio=0.3,
    min_size=100,
    set_sizes=(
        upset_set_size(
            geom=geom_bar(
                aes(fill=mpaa),
                stat='count',
                position='fill'
            )
        )
        + scale_x_continuous(labels=scales::percent_format())
    )
)
```

![image](https://user-images.githubusercontent.com/5832902/108056487-393aa400-7049-11eb-8543-cb3659a4c640.png)

**Comment by krassowski** [comment]
As for the error you posted:

```
Error in rep(value[[k]], length.out = n) :
attempt to replicate an object of type 'closure'
```

It appears to be because you are missing `aes()`: use `aes(fill=type)` instead of `fill=type`.

Please let me know if it helps.

**Comment by krassowski** [comment]
Example:

```R
upset(
    movies,
    genres,
    width_ratio=0.3,
    min_size=100,
    set_sizes=(
        upset_set_size(
            geom=geom_bar(
                aes(fill=mpaa),
                stat='count',
                position='fill'
            )
        )
        + scale_y_continuous(labels=scales::percent_format())
    )
)

```

![image](https://user-images.githubusercontent.com/5832902/108056696-8159c680-7049-11eb-9598-3c211513b695.png)

**Comment by krassowski** [comment]
I also removed a wrong comment of mine (sorry was too quick to comment on use of `coord_flip()`).

**Comment by zwangunc** [comment]
> I also removed a wrong comment of mine (sorry was too quick to comment on use of `coord_flip()`).

Hi Michał,

Thank you for the detailed answer. aes(fill=type) was the reason (coord_flip() is also a helpful idea). Now the issue has been resolved. I will try to use Patchwork to align/combine other bar plots. ComplexUpset is indeed a super cool package and I think there is still plenty of potentials. I will continue following the updates of it and exchanging ideas with you. Thank you again!
