### ISSUE TITLE
Showing empty plots when specifying intersections

### ISSUE THREAD

**Issue by sharathkmenon** [krassowski/complex-upset#99]
I want to make a set of plots for specified intersections. For uniformity between the graphs, I would like to display all the specified intersections, even if empty. Is there any way to do it in the current version? 

ComplexUpset version: 1.1.0

```R
<!-- R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS -->
```

**Comment by krassowski** [comment]
I don't think that it is possible with the current version. I do see a value in allowing to leave empty place for a non-existent intersection for the visual alignment purposes when comparing several plots. The limits of the x axis scale are currently hard-coded in:

https://github.com/krassowski/complex-upset/blob/7c2e1e46dff720dda183b596159f5031601aef4c/R/upset.R#L931-L933

It would be reasonable to allow to use the custom limits generated out of provided intersections variable. One would need to propose how to expose this functionality to the user (should it be a new argument? how to name it?).

**Comment by krassowski** [comment]
Changing the label to enhancement, because this feature sounds useful. It could be added in 1.2 version provided that there is some feedback on how the user API should work.

**Comment by krassowski** [comment]
This is now possible in the latest 1.2 version (not yet available on CRAN). To install it, use:

```R
if(!require(devtools)) install.packages("devtools")
devtools::install_github("krassowski/complex-upset")
```

And after restarting R you will be able to include empty intersections easily; for example, starting with:

```R
data = data.frame(matrix(data = TRUE, nrow=5, ncol=4))
data[5, 1] = FALSE
data[4, 2] = FALSE
data[, 4] = FALSE
data
```

![Screenshot from 2021-04-03 23-26-11](https://user-images.githubusercontent.com/5832902/113493038-0141d000-94d4-11eb-8708-efa1aacdd03b.png)

You can use:

```R
upset(
    data,
    c('X1', 'X2', 'X3', 'X4'),
    mode = "exclusive_intersection",
    sort_intersections = FALSE,
    intersections = list(
        c('X1', 'X2', 'X3'),  # existing intersection, 3 observations belong exclusively here
        c('X1', 'X2'),  # intersection exists in inclusive mode but not in exclusive
        c('X4'),   # this intersection is always empty as no observations belong to X4
        'Outside of known sets'  # members with no intersections (absent in this case)
    )
)
```

![image](https://user-images.githubusercontent.com/5832902/113493030-eff8c380-94d3-11eb-8988-6680562cd290.png)

or, similarly, but in inclusive mode:

```R
upset(
    data,
    c('X1', 'X2', 'X3', 'X4'),
    mode = "inclusive_intersection",
    sort_intersections = FALSE,
    intersections = list(
        c('X1', 'X2', 'X3'),  # existing intersection, 3 observations belong exclusively here
        c('X1', 'X2'),  # 3 members in inclusive mode
        c('X4'),   # this intersection is always empty as no observations belong to X4
        'Outside of known sets'  # members with no intersections (absent in this case)
    )
)
```

![image](https://user-images.githubusercontent.com/5832902/113493062-34845f00-94d4-11eb-8c46-b2679403a88c.png)

**Comment by sharathkmenon** [comment]
Hello, yes it works perfectly! Thank you very much!

It still gives an error for a particular edge case scenario. The plot throws an error if all the given intersections are NULL sets. 
I've defined a test dataframe below where none of the columns have any elements in common. 


```
data = data.frame(matrix(data = FALSE, nrow=5, ncol=4))
data[5, 1] = TRUE
data[4, 2] = TRUE
data[3, 3] = TRUE
data[2,4] = TRUE
```

![test](https://user-images.githubusercontent.com/52196306/113735116-91248b80-9719-11eb-8b32-9bdaec33e192.jpg)


now if we try to make an upset plot where none of the given intersections have elements in common:-

```
upset(
    data,
    c('X1', 'X2', 'X3', 'X4'),
    mode = "exclusive_intersection",
    sort_intersections = FALSE,
    intersections = list(
        c('X1', 'X2', 'X3'),  
        c('X1', 'X2'),  
        c('X3' , 'X4')
    )
)

```

It gives the following error:-


```
Error: Discrete value supplied to continuous scale
In addition: Warning messages:
1: In FUN(X[[i]], ...) : NAs introduced by coercion
2: In upset_data(data, intersect, mode = mode, encode_sets = encode_sets,  :
  None of the requested exclusive intersections is observed in the data:
  - requested: X1-X2-X3, X1-X2, X3-X4
  - available for exclusive intersection mode: NA, X4, X3, X2, X1
3: In max(exclusive_intersection_size, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
4: In max(exclusive_intersection_size, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf

```

**Comment by krassowski** [comment]
As a workaround you could use `base_annotations = list('Size'=intersection_size(counts=F)),`. Is this edge case important? The errors are coming from ggplot2 and it is not directly related to complex-upset per se. I can work around some of the ggplot2 edge cases (mostly dealing with missingness by pretending that NA are 0s) but this will complicate the codebase and may have little benefit.

**Comment by sharathkmenon** [comment]
Ah okay.
No, these edge cases aren't important for my work. I was just tinkering around and found this issue, thought I would mention it. 

Thank you very much!
